=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/DynamicData/ParametricDialog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:json="http://james.newtonking.com/projects/json" attributeFormDefault="unqualified"
  elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ParametricDialog" type="ParametricDialog"/>
  <xs:complexType name="FormLayoutItemDescriptor">
    <xs:sequence>
      <xs:element name="Caption" type="xs:string"/>
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="TypeCode">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Empty"/>
            <xs:enumeration value="Object"/>
            <xs:enumeration value="DBNull"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Char"/>
            <xs:enumeration value="SByte"/>
            <xs:enumeration value="Byte"/>
            <xs:enumeration value="Int16"/>
            <xs:enumeration value="UInt16"/>
            <xs:enumeration value="Int32"/>
            <xs:enumeration value="UInt32"/>
            <xs:enumeration value="Int64"/>
            <xs:enumeration value="UInt64"/>
            <xs:enumeration value="Single"/>
            <xs:enumeration value="Double"/>
            <xs:enumeration value="Decimal"/>
            <xs:enumeration value="DateTime"/>
            <xs:enumeration value="String"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="ParameterValueSourceType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="FromUser"/>
            <xs:enumeration value="FromSetting"/>
            <xs:enumeration value="FromInternalCode"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="NestedExtension">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Default"/>
            <xs:enumeration value="BinaryImage"/>
            <xs:enumeration value="Button"/>
            <xs:enumeration value="ButtonEdit"/>
            <xs:enumeration value="Calendar"/>
            <xs:enumeration value="Captcha"/>
            <xs:enumeration value="CheckBox"/>
            <xs:enumeration value="CheckBoxList"/>
            <xs:enumeration value="ColorEdit"/>
            <xs:enumeration value="ComboBox"/>
            <xs:enumeration value="DateEdit"/>
            <xs:enumeration value="DropDownEdit"/>
            <xs:enumeration value="HyperLink"/>
            <xs:enumeration value="Image"/>
            <xs:enumeration value="Label"/>
            <xs:enumeration value="ListBox"/>
            <xs:enumeration value="Memo"/>
            <xs:enumeration value="ProgressBar"/>
            <xs:enumeration value="RadioButton"/>
            <xs:enumeration value="RadioButtonList"/>
            <xs:enumeration value="SpinEdit"/>
            <xs:enumeration value="TextBox"/>
            <xs:enumeration value="TimeEdit"/>
            <xs:enumeration value="TokenBox"/>
            <xs:enumeration value="TrackBar"/>
            <xs:enumeration value="UploadControl"/>
            <xs:enumeration value="ValidationSummary"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="FormLayoutItemListBoxSetting">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="DataSourceType">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="Dictionary"/>
                  <xs:enumeration value="DictionaryWithAll"/>
                  <xs:enumeration value="DictionaryList"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="1" name="DataSource" type="xs:string"/>
            <xs:element minOccurs="0" name="FormLayoutItemListBoxColumns">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="FormLayoutItemListBoxColumn" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="FieldName" type="xs:string"/>
                        <xs:element name="Caption" type="xs:string"/>
                        <xs:element minOccurs="0" name="Width" type="xs:int"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Value" type="xs:string" minOccurs="0"/>
      <xs:element maxOccurs="unbounded" name="FormLayoutItemExtenders" type="FormLayoutItemExtender"
        minOccurs="0"/>
      <xs:element minOccurs="0" name="FormLayoutItemCustomData">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string"> </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute default="1" name="ClientVisible" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="FormLayoutItemExtender">
    <xs:sequence>
      <xs:element name="FormLayoutItemExtender" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="PropertiesChain" type="xs:string"/>
            <xs:element name="Value" type="xs:string"/>
            <xs:element name="TypeName" minOccurs="0">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="System.String"/>
                  <xs:enumeration value="System.Delegate"/>
                  <xs:enumeration value="System.Int32"/>
                  <xs:enumeration value="System.Boolean"/>
                  <xs:enumeration value="System.DateTime"/>
                  <xs:enumeration value="DevExpress.Web.ASPxEditors.EditFormat"/>
                  <xs:enumeration value="DevExpress.Web.ASPxEditors.Display"/>
                  <xs:enumeration value="DevExpress.Web.ASPxEditors.MaskIncludeLiteralsMode"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ParametricDialog">
    <xs:sequence>
      <xs:element name="Id" type="xs:string"/>
      <xs:element name="Height" type="xs:int"/>
      <xs:element name="Width" type="xs:int"/>
      <xs:element minOccurs="0" name="Modal" type="xs:boolean"/>
      <xs:element name="Buttons" type="Buttons"/>
      <xs:element name="Title" type="xs:string"/>
      <xs:element name="Descriptors" type="Descriptors"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Buttons">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="DialogButton" type="DialogButton"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Descriptors">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="FormLayoutItemDescriptor">
        <xs:complexType>
          <xs:complexContent>
            <xs:extension base="FormLayoutItemDescriptor"> </xs:extension>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DialogButton">
    <xs:sequence>
      <xs:element name="Title" type="xs:string"/>
      <xs:element name="Order" type="xs:int"/>
      <xs:element name="DialogModalResult">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Ok"/>
            <xs:enumeration value="Cancel"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/ParametricDialogs/Reports/GetAccountingParamSheetPramer710ParametricDialog.xml
<ParametricDialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ParametricDialog.xsd">
	<!--Парамерик отчета Почасовые мониторинговые показания  -->
	<Id>getAccountingParamSheetPramer710</Id>
	<Height>100</Height>
	<Width>400</Width>
	<Buttons>
		<DialogButton>
			<Title>OK</Title>
			<Order>0</Order>
			<DialogModalResult>Ok</DialogModalResult>
		</DialogButton>
		<DialogButton>
			<Title>Отмена</Title>
			<Order>1</Order>
			<DialogModalResult>Cancel</DialogModalResult>
		</DialogButton>
	</Buttons>
	<AllowResize>true</AllowResize>
  <ScrollBars>None</ScrollBars>
	<Title>Параметры</Title>
	<CloseAction>CloseButton</CloseAction>
	<IsSavedState>true</IsSavedState>
	<IsCollectInfoSnapshot>true</IsCollectInfoSnapshot>
	<InitScript HasEscapedContent="true">
    <![CDATA[
    function(sender, args)
    {      
    }
    ]]>
    </InitScript>
	<Descriptors>
		<FormLayoutItemDescriptor>
			<Caption></Caption>
			<Name>channelId</Name>
			<TypeCode>Int32</TypeCode>
			<ParameterValueSourceType>FromInternalCode</ParameterValueSourceType>
			<NestedExtension>Default</NestedExtension>
			<Value>0</Value>
		</FormLayoutItemDescriptor>
    
		<FormLayoutItemDescriptor>
			<Caption>Канал</Caption>
			<Name>channelId1</Name>
			<TypeCode>Int32</TypeCode>
			<ParameterValueSourceType>FromUser</ParameterValueSourceType>
			<NestedExtension>ComboBox</NestedExtension>
			<FormLayoutItemListBoxSetting>
				<DataSourceType>DictionaryByQuery</DataSourceType>
				<DataSource>DictionaryEntity</DataSource>
				<DataSourceQuery>
          SELECT
          [Ch].[Id] [Id],
          [Ch].[Description] [Code],
          [R].[Description] [Description]
				  
          FROM [Business].[Channel] [Ch] WITH(NOLOCK)
          INNER JOIN [Dictionaries].[ResourceSystemType] [R] WITH(NOLOCK)
          ON [Ch].[ResourceSystemTypeId] = [R].[Id]
          WHERE [Ch].[Id] = @channelId
        </DataSourceQuery>
				<FormLayoutItemListBoxColumns>
					<FormLayoutItemListBoxColumn>
						<FieldName>Id</FieldName>
						<Caption></Caption>
						<Width>20</Width>
					</FormLayoutItemListBoxColumn>
					<FormLayoutItemListBoxColumn>
						<FieldName>Code</FieldName>
						<Caption></Caption>
						<Width>100</Width>
					</FormLayoutItemListBoxColumn>
          
					<FormLayoutItemListBoxColumn>
						<FieldName>Description</FieldName>
						<Caption></Caption>
						<Width>200</Width>
					</FormLayoutItemListBoxColumn>
				    
				</FormLayoutItemListBoxColumns>
			</FormLayoutItemListBoxSetting>
			<Value>0</Value>
			<FormLayoutItemExtenders>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
					<Value>false</Value>
				</FormLayoutItemExtender>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
					<Value>Id</Value>
				</FormLayoutItemExtender>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
					<Value>Description</Value>
				</FormLayoutItemExtender>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
					<Value>{1}</Value>
				</FormLayoutItemExtender>
			</FormLayoutItemExtenders>
		</FormLayoutItemDescriptor>
    
		<FormLayoutItemDescriptor>
			<Caption>Начальная дата</Caption>
			<Name>periodBegin</Name>
			<TypeCode>DateTime</TypeCode>
			<ParameterValueSourceType>FromUser</ParameterValueSourceType>
			<NestedExtension>DateEdit</NestedExtension>
		</FormLayoutItemDescriptor>

		<FormLayoutItemDescriptor>
			<Caption>Конечная дата</Caption>
			<Name>periodEnd</Name>
			<TypeCode>DateTime</TypeCode>
			<ParameterValueSourceType>FromUser</ParameterValueSourceType>
			<NestedExtension>DateEdit</NestedExtension>
		</FormLayoutItemDescriptor>

    <FormLayoutItemDescriptor ClientVisible="true">
      <Caption>Включительно</Caption>
      <Name>includePeriodEnd</Name>
      <TypeCode>Boolean</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>CheckBox</NestedExtension>
    </FormLayoutItemDescriptor>
	</Descriptors>
</ParametricDialog>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/DynamicData/BetarECO211DynamicData.xml
<ParametricDialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ParametricDialog.xsd">
  <Id>pivotGridParametric</Id>
  <Height>0</Height>
  <Width>400</Width>
  <Buttons>
    <DialogButton>
      <Title>OK</Title>
      <Order>0</Order>
      <DialogModalResult>Ok</DialogModalResult>
    </DialogButton>
    <DialogButton>
      <Title>Отмена</Title>
      <Order>1</Order>
      <DialogModalResult>Cancel</DialogModalResult>
    </DialogButton>
  </Buttons>
  <Title>Параметры</Title>
  <Descriptors>
    <FormLayoutItemDescriptor>
      <Caption>Количество активных тарифов</Caption>
      <Name>ActiveTariffCount</Name>
      <TypeCode>Decimal</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>SpinEdit</NestedExtension>
      <Value>2</Value>
    </FormLayoutItemDescriptor>
    <FormLayoutItemDescriptor>
      <Caption>ID (общий тариф)</Caption>
      <Name>CommonTariffId</Name>
      <TypeCode>Decimal</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>SpinEdit</NestedExtension>
      <Value>0</Value>
    </FormLayoutItemDescriptor>
    <FormLayoutItemDescriptor>
      <Caption>ID (тариф 1)</Caption>
      <Name>Tariff1Id</Name>
      <TypeCode>Decimal</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>SpinEdit</NestedExtension>
      <Value>0</Value>
    </FormLayoutItemDescriptor>
    <FormLayoutItemDescriptor>
      <Caption>ID (тариф 2)</Caption>
      <Name>Tariff2Id</Name>
      <TypeCode>Decimal</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>SpinEdit</NestedExtension>
      <Value>0</Value>
    </FormLayoutItemDescriptor>
    <FormLayoutItemDescriptor>
      <Caption>ID (тариф 3)</Caption>
      <Name>Tariff3Id</Name>
      <TypeCode>Decimal</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>SpinEdit</NestedExtension>
      <Value>0</Value>
    </FormLayoutItemDescriptor>
    <FormLayoutItemDescriptor>
      <Caption>ID (тариф 4)</Caption>
      <Name>Tariff4Id</Name>
      <TypeCode>Decimal</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>SpinEdit</NestedExtension>
      <Value>0</Value>
    </FormLayoutItemDescriptor>
    <FormLayoutItemDescriptor>
      <Caption>Вес импульса</Caption>
      <Name>PulseWeight</Name>
      <TypeCode>Decimal</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>SpinEdit</NestedExtension>
      <Value>0.0002</Value>
    </FormLayoutItemDescriptor>
    <FormLayoutItemDescriptor>
      <Caption>Единица измерения веса импульса</Caption>
      <Name>MeasurementUnitId</Name>
      <TypeCode>Int32</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>ComboBox</NestedExtension>
      <FormLayoutItemListBoxSetting>
        <DataSourceType>Dictionary</DataSourceType>
        <DataSource>MeasurementUnit</DataSource>
        <FormLayoutItemListBoxColumns>
          <FormLayoutItemListBoxColumn>
            <FieldName>Id</FieldName>
            <Caption></Caption>
            <Width>20</Width>
          </FormLayoutItemListBoxColumn>
          <FormLayoutItemListBoxColumn>
            <FieldName>Code</FieldName>
            <Caption></Caption>
            <Width>100</Width>
          </FormLayoutItemListBoxColumn>
          <FormLayoutItemListBoxColumn>
            <FieldName>Description</FieldName>
            <Caption></Caption>
            <Width>200</Width>
          </FormLayoutItemListBoxColumn>
        </FormLayoutItemListBoxColumns>
      </FormLayoutItemListBoxSetting>
      <Value>20</Value>
      <FormLayoutItemExtenders>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
          <Value>Id</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
          <Value>Description</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
          <Value>{2}</Value>
        </FormLayoutItemExtender>
      </FormLayoutItemExtenders>
    </FormLayoutItemDescriptor>
    <FormLayoutItemDescriptor>
      <Caption>Размерность веса импульса</Caption>
      <Name>DimensionId</Name>
      <TypeCode>Int32</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>ComboBox</NestedExtension>
      <FormLayoutItemListBoxSetting>
        <DataSourceType>Dictionary</DataSourceType>
        <DataSource>Dimension</DataSource>
        <FormLayoutItemListBoxColumns>
          <FormLayoutItemListBoxColumn>
            <FieldName>Id</FieldName>
            <Caption></Caption>
            <Width>20</Width>
          </FormLayoutItemListBoxColumn>
          <FormLayoutItemListBoxColumn>
            <FieldName>Code</FieldName>
            <Caption></Caption>
            <Width>100</Width>
          </FormLayoutItemListBoxColumn>
          <FormLayoutItemListBoxColumn>
            <FieldName>Description</FieldName>
            <Caption></Caption>
            <Width>200</Width>
          </FormLayoutItemListBoxColumn>
        </FormLayoutItemListBoxColumns>
      </FormLayoutItemListBoxSetting>
      <Value>3</Value>
      <FormLayoutItemExtenders>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
          <Value>Id</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
          <Value>Description</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
          <Value>{2}</Value>
        </FormLayoutItemExtender>
      </FormLayoutItemExtenders>
    </FormLayoutItemDescriptor>
  </Descriptors>
</ParametricDialog>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/ParametricDialogs/BuildingAddressDialog.xml
<ParametricDialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                  xsi:noNamespaceSchemaLocation="ParametricDialog.xsd">
  
  <!--Описывает диалоговое окно для ручного ввода компонентов адреса на форме "Строения"-->
  <Id>buildingAddressDialog</Id>
  <Height>0</Height>
  <Width>450</Width>
  <Buttons>
    <DialogButton>
      <Title>OK</Title>
      <Order>0</Order>
      <DialogModalResult>Ok</DialogModalResult>
    </DialogButton>
    <DialogButton>
      <Title>Отмена</Title>
      <Order>1</Order>
      <DialogModalResult>Cancel</DialogModalResult>
    </DialogButton>
  </Buttons>
  <Title>Редактирование компонентов адреса</Title>
  <IsSavedState>false</IsSavedState>
  <Descriptors>

    <FormLayoutItemDescriptor>
      <Caption>Улица</Caption>
      <Name>street</Name>
      <TypeCode>String</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>TextBox</NestedExtension>
    </FormLayoutItemDescriptor>

    <FormLayoutItemDescriptor>
      <Caption>Номер дома</Caption>
      <Name>buildingNumber</Name>
      <TypeCode>String</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>TextBox</NestedExtension>
    </FormLayoutItemDescriptor>

    <FormLayoutItemDescriptor>
      <Caption>Город</Caption>
      <Name>city</Name>
      <TypeCode>String</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>ComboBox</NestedExtension>
      <FormLayoutItemListBoxSetting>
        <DataSourceType>Dictionary</DataSourceType>
        <DataSource>City</DataSource>
        <FormLayoutItemListBoxColumns>
          <FormLayoutItemListBoxColumn>
            <FieldName>Description</FieldName>
            <Caption>Наименование</Caption>
            <Width>400</Width>
          </FormLayoutItemListBoxColumn>
        </FormLayoutItemListBoxColumns>
      </FormLayoutItemListBoxSetting>
      <FormLayoutItemExtenders>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
          <Value>Description</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
          <Value>Description</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
          <Value>{0}</Value>
        </FormLayoutItemExtender>
      </FormLayoutItemExtenders>
    </FormLayoutItemDescriptor>

    <FormLayoutItemDescriptor>
      <Caption>Регион</Caption>
      <Name>region</Name>
      <TypeCode>String</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>TextBox</NestedExtension>
      <FormLayoutItemExtenders>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
          <Value>false</Value>
        </FormLayoutItemExtender>
      </FormLayoutItemExtenders>
    </FormLayoutItemDescriptor>

    <FormLayoutItemDescriptor>
      <Caption>Страна</Caption>
      <Name>country</Name>
      <TypeCode>String</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>TextBox</NestedExtension>
      <FormLayoutItemExtenders>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
          <Value>false</Value>
        </FormLayoutItemExtender>
      </FormLayoutItemExtenders>
    </FormLayoutItemDescriptor>

    <FormLayoutItemDescriptor>
      <Caption>Почтовый индекс</Caption>
      <Name>postCode</Name>
      <TypeCode>String</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>TextBox</NestedExtension>
      <FormLayoutItemExtenders>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
          <Value>false</Value>
        </FormLayoutItemExtender>
      </FormLayoutItemExtenders>
    </FormLayoutItemDescriptor>

  </Descriptors>
</ParametricDialog>
