=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/DynamicData/ParametricDialog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:json="http://james.newtonking.com/projects/json" attributeFormDefault="unqualified"
  elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ParametricDialog" type="ParametricDialog"/>
  <xs:complexType name="FormLayoutItemDescriptor">
    <xs:sequence>
      <xs:element name="Caption" type="xs:string"/>
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="TypeCode">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Empty"/>
            <xs:enumeration value="Object"/>
            <xs:enumeration value="DBNull"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Char"/>
            <xs:enumeration value="SByte"/>
            <xs:enumeration value="Byte"/>
            <xs:enumeration value="Int16"/>
            <xs:enumeration value="UInt16"/>
            <xs:enumeration value="Int32"/>
            <xs:enumeration value="UInt32"/>
            <xs:enumeration value="Int64"/>
            <xs:enumeration value="UInt64"/>
            <xs:enumeration value="Single"/>
            <xs:enumeration value="Double"/>
            <xs:enumeration value="Decimal"/>
            <xs:enumeration value="DateTime"/>
            <xs:enumeration value="String"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="ParameterValueSourceType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="FromUser"/>
            <xs:enumeration value="FromSetting"/>
            <xs:enumeration value="FromInternalCode"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="NestedExtension">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Default"/>
            <xs:enumeration value="BinaryImage"/>
            <xs:enumeration value="Button"/>
            <xs:enumeration value="ButtonEdit"/>
            <xs:enumeration value="Calendar"/>
            <xs:enumeration value="Captcha"/>
            <xs:enumeration value="CheckBox"/>
            <xs:enumeration value="CheckBoxList"/>
            <xs:enumeration value="ColorEdit"/>
            <xs:enumeration value="ComboBox"/>
            <xs:enumeration value="DateEdit"/>
            <xs:enumeration value="DropDownEdit"/>
            <xs:enumeration value="HyperLink"/>
            <xs:enumeration value="Image"/>
            <xs:enumeration value="Label"/>
            <xs:enumeration value="ListBox"/>
            <xs:enumeration value="Memo"/>
            <xs:enumeration value="ProgressBar"/>
            <xs:enumeration value="RadioButton"/>
            <xs:enumeration value="RadioButtonList"/>
            <xs:enumeration value="SpinEdit"/>
            <xs:enumeration value="TextBox"/>
            <xs:enumeration value="TimeEdit"/>
            <xs:enumeration value="TokenBox"/>
            <xs:enumeration value="TrackBar"/>
            <xs:enumeration value="UploadControl"/>
            <xs:enumeration value="ValidationSummary"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="0" name="FormLayoutItemListBoxSetting">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="1" name="DataSourceType">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="Dictionary"/>
                  <xs:enumeration value="DictionaryWithAll"/>
                  <xs:enumeration value="DictionaryList"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="1" name="DataSource" type="xs:string"/>
            <xs:element minOccurs="0" name="FormLayoutItemListBoxColumns">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="FormLayoutItemListBoxColumn" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="FieldName" type="xs:string"/>
                        <xs:element name="Caption" type="xs:string"/>
                        <xs:element minOccurs="0" name="Width" type="xs:int"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Value" type="xs:string" minOccurs="0"/>
      <xs:element maxOccurs="unbounded" name="FormLayoutItemExtenders" type="FormLayoutItemExtender"
        minOccurs="0"/>
      <xs:element minOccurs="0" name="FormLayoutItemCustomData">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string"> </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute default="1" name="ClientVisible" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="FormLayoutItemExtender">
    <xs:sequence>
      <xs:element name="FormLayoutItemExtender" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="PropertiesChain" type="xs:string"/>
            <xs:element name="Value" type="xs:string"/>
            <xs:element name="TypeName" minOccurs="0">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="System.String"/>
                  <xs:enumeration value="System.Delegate"/>
                  <xs:enumeration value="System.Int32"/>
                  <xs:enumeration value="System.Boolean"/>
                  <xs:enumeration value="System.DateTime"/>
                  <xs:enumeration value="DevExpress.Web.ASPxEditors.EditFormat"/>
                  <xs:enumeration value="DevExpress.Web.ASPxEditors.Display"/>
                  <xs:enumeration value="DevExpress.Web.ASPxEditors.MaskIncludeLiteralsMode"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ParametricDialog">
    <xs:sequence>
      <xs:element name="Id" type="xs:string"/>
      <xs:element name="Height" type="xs:int"/>
      <xs:element name="Width" type="xs:int"/>
      <xs:element minOccurs="0" name="Modal" type="xs:boolean"/>
      <xs:element name="Buttons" type="Buttons"/>
      <xs:element name="Title" type="xs:string"/>
      <xs:element name="Descriptors" type="Descriptors"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Buttons">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="DialogButton" type="DialogButton"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Descriptors">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="FormLayoutItemDescriptor">
        <xs:complexType>
          <xs:complexContent>
            <xs:extension base="FormLayoutItemDescriptor"> </xs:extension>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DialogButton">
    <xs:sequence>
      <xs:element name="Title" type="xs:string"/>
      <xs:element name="Order" type="xs:int"/>
      <xs:element name="DialogModalResult">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Ok"/>
            <xs:enumeration value="Cancel"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/ParametricDialogs/MeasurementDeviceDistributionParametricDialog.xml
<ParametricDialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ParametricDialog.xsd">
  <!--Параметрик для сводной таблицы Распределение измерительных приборов-->
  <Id>measurementDeviceDistributionParametricDialog</Id>
  <Height>0</Height>
  <Width>400</Width>
  <Buttons>
    <DialogButton>
      <Title>OK</Title>
      <Order>0</Order>
      <DialogModalResult>Ok</DialogModalResult>
    </DialogButton>
    <DialogButton>
      <Title>Отмена</Title>
      <Order>1</Order>
      <DialogModalResult>Cancel</DialogModalResult>
    </DialogButton>
  </Buttons>
  <Title>Параметры</Title>
  <IsSavedState>true</IsSavedState>
  <IsCollectInfoSnapshot>true</IsCollectInfoSnapshot>
  <Descriptors>

    <FormLayoutItemDescriptor>
      <Caption>Город</Caption>
      <Name>CityId</Name>
      <TypeCode>Int32</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>ComboBox</NestedExtension>
      <FormLayoutItemListBoxSetting>
        <DataSourceType>DictionaryWithAll</DataSourceType>
        <DataSource>City</DataSource>
        <FormLayoutItemListBoxColumns>
          <FormLayoutItemListBoxColumn>
            <FieldName>Id</FieldName>
            <Caption></Caption>
            <Width>20</Width>
          </FormLayoutItemListBoxColumn>
          <FormLayoutItemListBoxColumn>
            <FieldName>Code</FieldName>
            <Caption></Caption>
            <Width>100</Width>
          </FormLayoutItemListBoxColumn>
          <FormLayoutItemListBoxColumn>
            <FieldName>Description</FieldName>
            <Caption></Caption>
            <Width>200</Width>
          </FormLayoutItemListBoxColumn>
        </FormLayoutItemListBoxColumns>
      </FormLayoutItemListBoxSetting>
      <Value>0</Value>
      <FormLayoutItemExtenders>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
          <Value>false</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
          <Value>Id</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
          <Value>Description</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
          <Value>{2}</Value>
        </FormLayoutItemExtender>
      </FormLayoutItemExtenders>
    </FormLayoutItemDescriptor>

    <FormLayoutItemDescriptor>
      <Caption></Caption>
      <Name>PivotFields</Name>
      <TypeCode>String</TypeCode>
      <ParameterValueSourceType>FromSetting</ParameterValueSourceType>
      <NestedExtension>Default</NestedExtension>
      <FormLayoutItemCustomData>
        [{
        "area": "RowArea",
        "areaIndex": 0,
        "fieldName":"City",
        "caption":"Город",
        "visible": 1
        },
        {
        "area": "RowArea",
        "areaIndex": 1,
        "fieldName":"District",
        "caption":"Район",
        "visible": 1
        },        
        {
        "area": "ColumnArea",
        "areaIndex": 1,
        "fieldName":"Device",
        "caption":"Тип прибора",
        "visible": 1
        },
        {
        "area": "DataArea",
        "areaIndex": 0,
        "fieldName":"Count",
        "caption":"Количество",
        "visible": 1
        },
        {
        "area": "FilterArea",
        "areaIndex": 0,
        "fieldName":"Building",
        "caption":"Строение",
        "visible": 1
        },
        {
        "area": "FilterArea",
        "areaIndex": 1,
        "fieldName":"AccessPoint",
        "caption":"Точка доступа",
        "visible": 1
        },
        {
        "area": "FilterArea",
        "areaIndex": 2,
        "fieldName":"MeasurementDevice",
        "caption":"Прибор",
        "visible": 1
        },
        {
        "area": "FilterArea",
        "areaIndex": 3,
        "fieldName":"ConnectionsNumber",
        "caption":"Число соединений",
        "visible": 1
        },
        {
        "area": "FilterArea",
        "areaIndex": 4,
        "fieldName":"GoodResponsePercent",
        "caption":"Процент успешных соединений",
        "visible": 1
        },
        {
        "area": "FilterArea",
        "areaIndex": 5,
        "fieldName":"Id",
        "caption":"Ид",
        "visible": 0
        },
        {
        "area": "FilterArea",
        "areaIndex": 7,
        "fieldName":"DeviceReaderDescription",
        "caption": "Считыватель",
        "visible": 1
        }]
      </FormLayoutItemCustomData>
    </FormLayoutItemDescriptor>

  </Descriptors>
</ParametricDialog>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/ParametricDialogs/GetParametersInfoByDeviceParametricDialog.xml
<ParametricDialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ParametricDialog.xsd">
  <!--Парамерик для выбора типа измерительного прибора для запроса по списку соотвествия пареметров -->
  <Id>getParametersInfoByDeviceParametricDialog</Id>
  <Height>100</Height>
  <Width>400</Width>
  <Buttons>
    <DialogButton>
      <Title>OK</Title>
      <Order>0</Order>
      <DialogModalResult>Ok</DialogModalResult>
    </DialogButton>
    <DialogButton>
      <Title>Отмена</Title>
      <Order>1</Order>
      <DialogModalResult>Cancel</DialogModalResult>
    </DialogButton>
  </Buttons>
  <Title>Параметры</Title>
  <IsSavedState>true</IsSavedState>
  <IsCollectInfoSnapshot>true</IsCollectInfoSnapshot>
  <Descriptors>
    <FormLayoutItemDescriptor>
      <Caption>Тип измерительного прибора</Caption>
      <Name>deviceId</Name>
      <TypeCode>String</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>ComboBox</NestedExtension>      
      <FormLayoutItemListBoxSetting>        
        <DataSourceType>DictionaryWithAll</DataSourceType>
        <DataSource>Device</DataSource>        
        <FormLayoutItemListBoxColumns>
          <FormLayoutItemListBoxColumn>
            <FieldName>Id</FieldName>
            <Caption></Caption>
            <Width>20</Width>
          </FormLayoutItemListBoxColumn>
          <FormLayoutItemListBoxColumn>
            <FieldName>Code</FieldName>
            <Caption></Caption>
            <Width>100</Width>
          </FormLayoutItemListBoxColumn>
          <FormLayoutItemListBoxColumn>
            <FieldName>Description</FieldName>
            <Caption></Caption>
            <Width>200</Width>
          </FormLayoutItemListBoxColumn>
        </FormLayoutItemListBoxColumns>
      </FormLayoutItemListBoxSetting>
      <FormLayoutItemExtenders>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
          <Value>Id</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
          <Value>Description</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
          <Value>{2}</Value>
        </FormLayoutItemExtender>                
      </FormLayoutItemExtenders>
    </FormLayoutItemDescriptor>    
  </Descriptors>
</ParametricDialog>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/ParametricDialogs/EntitiesParametricDialogs/Binary.xml
<ParametricDialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\ParametricDialog.xsd">
	<Id>gridEditBinaryDialog</Id>
	<Width>400</Width>
	<Modal>true</Modal>
	<CloseAction>CloseButton</CloseAction>
	<ScrollBars>None</ScrollBars>
	<AllowResize>true</AllowResize>
	<ShowHeader>true</ShowHeader>
	<ShowFooter>true</ShowFooter>
	<DragElement>Header</DragElement>
	<PopupHorizontalAlign>WindowCenter</PopupHorizontalAlign>
	<PopupVerticalAlign>WindowCenter</PopupVerticalAlign>
	<Buttons>
		<DialogButton>
			<Title>ОК</Title>
			<Order>0</Order>
			<DialogModalResult>Ok</DialogModalResult>
		</DialogButton>
		<DialogButton>
			<Title>Отмена</Title>
			<Order>1</Order>
			<DialogModalResult>Cancel</DialogModalResult>
		</DialogButton>
	</Buttons>
	<IsNotInline>false</IsNotInline>
	<IsSavedState>false</IsSavedState>
	<Descriptors>
		<FormLayoutItemDescriptor ClientVisible="true">
			<Name>Id_Binary</Name>
			<Caption>Ид</Caption>
			<TypeCode>Int32</TypeCode>
			<NestedExtension>SpinEdit</NestedExtension>
			<ParameterValueSourceType>FromUser</ParameterValueSourceType>
			<Value>1</Value>
			<FormLayoutItemExtenders>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.Enabled</PropertiesChain>
					<Value>false</Value>
				</FormLayoutItemExtender>
			</FormLayoutItemExtenders>
		</FormLayoutItemDescriptor>
		<FormLayoutItemDescriptor ClientVisible="true">
			<Name>Code_Binary</Name>
			<Caption>Код</Caption>
			<TypeCode>String</TypeCode>
			<NestedExtension>ButtonEdit</NestedExtension>
			<FormLayoutItemExtenders>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.Properties.MaxLength</PropertiesChain>
					<Value>64</Value>
				</FormLayoutItemExtender>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.Properties.Buttons.Add()</PropertiesChain>
					<Value></Value>
					<TypeName>System.Delegate</TypeName>
				</FormLayoutItemExtender>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
					<Value>false</Value>
				</FormLayoutItemExtender>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.Properties.ClientSideEvents.Init</PropertiesChain>
					<Value HasEscapedContent="true">
                function(sender, args)
                {
                  var context$ = jQuery(sender.GetMainElement());
                  jQuery(".dxeButton:last img", context$).hide();                  
                  jQuery(".dxeButton:last", context$).append(jQuery("&lt;i style=&apos;margin-right: 2px&apos; class=&apos;font-icon-keys&apos; title=&apos;Генерировать последовательность символов&apos;&apos;&gt;&lt;i/&gt;"));                  
                }
                </Value>
				</FormLayoutItemExtender>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.Properties.ClientSideEvents.ButtonClick</PropertiesChain>
					<Value HasEscapedContent="true">
            function(sender, args)
            {                            
                  $.ajax({
                    url: Core.Routes.Common.InternalApi.getGeneratedCharset,
                    type: Core.Common.HttpRequestTypes.Post,
                    dataType: Core.Common.HttpDataTypes.Json,
                    data:
                    {
                        length: 16,
                        onlySymbols: true
                    }
                  }).fail(function(response)
                  {
                      $.event.trigger(Core.Common.EventTypes.CoreAsyncError);
                  }).done(function(response)
                  {            
                      sender.SetText(response);                      
                  });              
            }
            </Value>
				</FormLayoutItemExtender>
			</FormLayoutItemExtenders>
			<ParameterValueSourceType>FromUser</ParameterValueSourceType>
			<Value>StartUp</Value>
		</FormLayoutItemDescriptor>
		<FormLayoutItemDescriptor ClientVisible="true">
			<Name>Description_Binary</Name>
			<Caption>Наименование</Caption>
			<TypeCode>String</TypeCode>
			<NestedExtension>ButtonEdit</NestedExtension>
			<ParameterValueSourceType>FromUser</ParameterValueSourceType>
			<Value>Старт разработки проекта</Value>
		</FormLayoutItemDescriptor>
		<FormLayoutItemDescriptor ClientVisible="true">
			<Name>BinaryContentTypeId_Binary</Name>
			<Caption>Тип бинарного содержимого</Caption>
			<TypeCode>Int32</TypeCode>
			<NestedExtension>ComboBox</NestedExtension>
			<ParameterValueSourceType>FromUser</ParameterValueSourceType>
			<FormLayoutItemListBoxSetting>
				<DataSource>BinaryContentType</DataSource>
				<DataSourceType>Dictionary</DataSourceType>
				<FormLayoutItemListBoxColumns>
					<FormLayoutItemListBoxColumn>
						<FieldName>Id</FieldName>
						<Width>20</Width>
					</FormLayoutItemListBoxColumn>
					<FormLayoutItemListBoxColumn>
						<FieldName>Code</FieldName>
						<Width>100</Width>
					</FormLayoutItemListBoxColumn>
					<FormLayoutItemListBoxColumn>
						<FieldName>Description</FieldName>
						<Width>200</Width>
					</FormLayoutItemListBoxColumn>
				</FormLayoutItemListBoxColumns>
			</FormLayoutItemListBoxSetting>
			<Value>8</Value>
			<FormLayoutItemExtenders>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
					<Value>Id</Value>
				</FormLayoutItemExtender>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
					<Value>Description</Value>
				</FormLayoutItemExtender>
				<FormLayoutItemExtender>
					<PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
					<Value>{2}</Value>
				</FormLayoutItemExtender>
			</FormLayoutItemExtenders>
		</FormLayoutItemDescriptor>
		<FormLayoutItemDescriptor ClientVisible="true">
			<Name>Category_Binary</Name>
			<Caption>Категория</Caption>
			<TypeCode>String</TypeCode>
			<NestedExtension>ButtonEdit</NestedExtension>
			<ParameterValueSourceType>FromUser</ParameterValueSourceType>
			<Value>News</Value>
		</FormLayoutItemDescriptor>
	</Descriptors>
</ParametricDialog>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/ParametricDialogs/FlatDevicesConnectionQualityParametricDialog.xml
<ParametricDialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="ParametricDialog.xsd">
  <Id>FlatDevicesConnectionQualityParametricDialog</Id>
  <Height>0</Height>
  <Width>350</Width>
  <Buttons>
    <DialogButton>
      <Title>OK</Title>
      <Order>0</Order>
      <DialogModalResult>Ok</DialogModalResult>
    </DialogButton>
    <DialogButton>
      <Title>Отмена</Title>
      <Order>1</Order>
      <DialogModalResult>Cancel</DialogModalResult>
    </DialogButton>
  </Buttons>
  <Title>Параметры</Title>
  <IsSavedState>false</IsSavedState>

  <Descriptors>
    <FormLayoutItemDescriptor>
      <Caption>Строение</Caption>
      <Name>BuildingId</Name>
      <TypeCode>Int32</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>ComboBox</NestedExtension>
      <FormLayoutItemListBoxSetting>
        <DataSourceType>DictionaryByQuery</DataSourceType>
        <DataSource>DictionaryEntity</DataSource>
        <DataSourceQuery>
          SELECT DISTINCT([B].[Id]) [Id],
          [B].[Description] [Description]
          FROM [Business].[Building] [B] WITH(NOLOCK)
          INNER JOIN [Business].[AccessPointLinkBuilding] [Aplb] WITH(NOLOCK) ON [Aplb].[BuildingId] = [B].[Id]
          INNER JOIN [Business].[AccessPoint] [Ap] WITH(NOLOCK) ON [Aplb].[AccessPointId] = [Ap].[Id]
          INNER JOIN [Business].[MeasurementDevice] [Md] WITH(NOLOCK) ON [Ap].[Id] = [Md].[AccessPointId]
          INNER JOIN [Business].[Channel] [Channel] WITH(NOLOCK) ON [Md].[Id] = [Channel].[MeasurementDeviceId]
          INNER JOIN [Business].[Placement] [P] WITH(NOLOCK) ON [P].[BuildingId] = [B].[Id] AND [P].[PlacementPurposeId] = 1
          WHERE [Channel].[Id]  IN
          (
          SELECT [Ul].[ChannelId]
          FROM [Business].[UserLinkChannel] [Ul] WITH(NOLOCK)
          WHERE [Ul].[UserId] = (SELECT TOP(1) [User].[Id] FROM [Admin].[User] [User] WITH(NOLOCK) WHERE [User].[UserName] = @userName)
          ) OR &apos;ADMIN&apos; = @roleName

          UNION
          SELECT 0 [Id], &apos;Все строения&apos; [Description]
          ORDER BY [Id]
        </DataSourceQuery>
        <FormLayoutItemListBoxColumns>
          <FormLayoutItemListBoxColumn>
            <FieldName>Id</FieldName>
            <Caption>Ид</Caption>
            <Width>20</Width>
          </FormLayoutItemListBoxColumn>
          <FormLayoutItemListBoxColumn>
            <FieldName>Description</FieldName>
            <Caption>Наименование</Caption>
            <Width>300</Width>
          </FormLayoutItemListBoxColumn>
        </FormLayoutItemListBoxColumns>
      </FormLayoutItemListBoxSetting>
      <FormLayoutItemExtenders>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
          <Value>Id</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
          <Value>Description</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
          <Value>{1}</Value>
        </FormLayoutItemExtender>
      </FormLayoutItemExtenders>
    </FormLayoutItemDescriptor>

    <FormLayoutItemDescriptor>
      <Caption>Тип ресурсной системы</Caption>
      <Name>ResourceSystemTypeId</Name>
      <TypeCode>String</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>ComboBox</NestedExtension>
      <FormLayoutItemListBoxSetting>
        <DataSourceType>DictionaryWithAll</DataSourceType>
        <DataSource>ResourceSystemType</DataSource>
        <FormLayoutItemListBoxColumns>
          <FormLayoutItemListBoxColumn>
            <FieldName>Id</FieldName>
            <Caption></Caption>
            <Width>20</Width>
          </FormLayoutItemListBoxColumn>
          <FormLayoutItemListBoxColumn>
            <FieldName>Description</FieldName>
            <Caption></Caption>
            <Width>300</Width>
          </FormLayoutItemListBoxColumn>
        </FormLayoutItemListBoxColumns>
      </FormLayoutItemListBoxSetting>
      <Value>0</Value>
      <FormLayoutItemExtenders>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
          <Value>Id</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
          <Value>Description</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
          <Value>{1}</Value>
        </FormLayoutItemExtender>
      </FormLayoutItemExtenders>
    </FormLayoutItemDescriptor>

    <FormLayoutItemDescriptor>
      <Caption>Статус подключения прибора</Caption>
      <Name>DeviceStatusId</Name>
      <TypeCode>String</TypeCode>
      <ParameterValueSourceType>FromUser</ParameterValueSourceType>
      <NestedExtension>ComboBox</NestedExtension>
      <FormLayoutItemListBoxSetting>
        <DataSourceType>DictionaryWithAll</DataSourceType>
        <DataSource>StatusConnection</DataSource>
        <FormLayoutItemListBoxColumns>
          <FormLayoutItemListBoxColumn>
            <FieldName>Id</FieldName>
            <Caption></Caption>
            <Width>20</Width>
          </FormLayoutItemListBoxColumn>
          <FormLayoutItemListBoxColumn>
            <FieldName>Description</FieldName>
            <Caption></Caption>
            <Width>300</Width>
          </FormLayoutItemListBoxColumn>
        </FormLayoutItemListBoxColumns>
      </FormLayoutItemListBoxSetting>
      <Value>0</Value>
      <FormLayoutItemExtenders>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
          <Value>Id</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
          <Value>Description</Value>
        </FormLayoutItemExtender>
        <FormLayoutItemExtender>
          <PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
          <Value>{1}</Value>
        </FormLayoutItemExtender>
      </FormLayoutItemExtenders>
    </FormLayoutItemDescriptor>
  </Descriptors>
</ParametricDialog>
