=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/Forms/FormLayout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:attribute default="false" name="HasEscapedContent" type="xs:boolean"/>
    <xs:element name="FormLayout">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ColCount" type="xs:unsignedInt"/>
                <xs:element name="ItemHeight" type="xs:unsignedInt"/>
                <xs:element name="Width" type="xs:unsignedInt"/>
                <xs:element maxOccurs="1" minOccurs="0" name="InitScript">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute ref="HasEscapedContent" use="optional"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="1" minOccurs="0" name="InitStyle" type="xs:string"/>
                <xs:element minOccurs="0" ref="CommandMenu"/>
                <xs:element name="FormLayoutGroups">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="FormLayoutGroup">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="FormLayoutItems">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded"
                                                  name="FormLayoutItem">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="BoundProperty"/>
                                                  <xs:element name="NestedExtension">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="TextBox"/>
                                                  <xs:enumeration value="SpinEdit"/>
                                                  <xs:enumeration value="TimeEdit"/>
                                                  <xs:enumeration value="TrackBar"/>
                                                  <xs:enumeration value="DateEdit"/>
                                                  <xs:enumeration value="CheckBox"/>
                                                  <xs:enumeration value="ButtonEdit"/>
                                                  <xs:enumeration value="Memo"/>
                                                  <xs:enumeration value="ComboBox"/>
                                                  <xs:enumeration value="ListBox"/>
                                                  <xs:enumeration value="Default"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element minOccurs="0" name="IsNotClonable"
                                                  type="xs:boolean"/>
                                                  <xs:element minOccurs="0" name="Tooltip">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element minOccurs="0" name="HelpId"
                                                  type="xs:int"/>
                                                  <xs:element minOccurs="1" name="Text"
                                                  type="xs:string"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element minOccurs="0"
                                                  name="FormLayoutItemExtenders">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded"
                                                  name="FormLayoutItemExtender">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="PropertiesChain"
                                                  type="xs:string"/>
                                                  <xs:element name="Value">
                                                  <xs:complexType>
                                                  <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute ref="HasEscapedContent"
                                                  use="optional"/>
                                                  </xs:extension>
                                                  </xs:simpleContent>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="TypeName" minOccurs="0">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="System.String"/>
                                                  <xs:enumeration value="System.Delegate"/>
                                                  <xs:enumeration value="System.Int32"/>
                                                  <xs:enumeration value="System.Boolean"/>
                                                  <xs:enumeration value="System.DateTime"/>
                                                  <xs:enumeration
                                                  value="DevExpress.Web.ASPxEditors.EditFormat"/>
                                                  <xs:enumeration
                                                  value="DevExpress.Web.ASPxEditors.Display"/>
                                                  <xs:enumeration
                                                  value="DevExpress.Web.ASPxEditors.MaskIncludeLiteralsMode"
                                                  />
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element minOccurs="0"
                                                  ref="FormLayoutItemListBoxSetting"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="Caption" type="xs:string"/>
                                                  <xs:attribute name="Order" type="xs:unsignedInt"/>
                                                  <xs:attribute name="Enabled" type="xs:boolean"/>
                                                  <xs:attribute name="ClientVisible"
                                                  type="xs:boolean" use="optional"/>
                                                  <xs:attribute name="IsGrid" type="xs:boolean"
                                                  use="optional"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="Caption" type="xs:string"/>
                                    <xs:attribute name="ColSpan" type="xs:unsignedInt"/>
                                    <xs:attribute name="Order" type="xs:unsignedInt"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="CommandMenuItem">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="CommandMenuItem"/>
                <xs:element name="AdditionalInfo" type="xs:string"/>
                <xs:element name="BeginGroup" type="xs:boolean"/>
                <xs:element name="CommandName" type="xs:string"/>
                <xs:element name="Enabled" type="xs:boolean"/>
                <xs:element name="IconClass" type="xs:string"/>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Text" type="xs:string"/>
                <xs:element name="ToolTip" type="xs:string"/>
                <xs:element maxOccurs="1" minOccurs="0" name="Checked" type="xs:boolean"/>
                <xs:element minOccurs="0" name="GroupName" type="xs:string"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="CommandMenu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="ClientVisible" type="xs:boolean"/>
                <xs:element maxOccurs="1" minOccurs="1" name="Width" type="xs:int"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="CommandMenuItem"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="FormLayoutItemListBoxSetting">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" name="DataSourceType">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Dictionary"/>
                            <xs:enumeration value="DictionaryWithAll"/>
                            <xs:enumeration value="DictionaryList"/>
                            <xs:enumeration value="DictionaryByQuery"/>
                            <xs:enumeration value="Entity"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="1" name="DataSource" type="xs:string"/>
                <xs:element minOccurs="0" name="DataSourceQuery" type="xs:string"/>
                <xs:element minOccurs="0" name="FormLayoutItemListBoxColumns">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="FormLayoutItemListBoxColumn">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="FieldName" type="xs:string"/>
                                        <xs:element name="Caption" type="xs:string"/>
                                        <xs:element minOccurs="0" name="Width" type="xs:int"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/Forms/SystemSettingForm.xml
<FormLayout Name="systemSettingForm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FormLayout.xsd">
	<ColCount>2</ColCount>
	<ItemHeight>32</ItemHeight>
	<Width>500</Width>
	<InitScript HasEscapedContent="true">
    function(sender, args)
    {             
        var formController = Core.Admin.FormController.prototype.currentInstance;

        formController.setModelValidator(function(model)
        {
            var result = true;    
            
            var validationState = 
            {
              isValid: result,
              visualizationMethod: Core.Admin.FormController.ValidationVisualizationMethod.MessageBox,
              validationSourceInfo: []
            };
            
            try
            {
              (JSON.parse(model.customData));
            }
            catch (e)
            {
              result = false;
            }

            if (result !== true)
            {
                validationState.validationSourceInfo.push(
                {                   
                    fieldName: "customData",
                    sourceFieldName: "CustomData",
                    sourceCaption: "Дополнительные настройки",                                       
                    message: "Содержимое поля не является корректным JSON форматом."
                });
            }

            validationState.isValid = result;
            
            return validationState;
        });       
    }
    </InitScript>
	<InitStyle HasEscapedContent="true">
    .CodeMirror
    {
      line-height: 1.5;
      height: auto;
    }
    </InitStyle>
	<FormLayoutGroups>
		<FormLayoutGroup Caption="Идентифицирующие" ColSpan="2" Order="1">
			<FormLayoutItems>
				<FormLayoutItem Caption="Ид" Enabled="false" Order="1">
					<BoundProperty>Id</BoundProperty>
					<NestedExtension>SpinEdit</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
							<Value>true</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Наименование" Enabled="true" Order="1">
					<BoundProperty>SystemName</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
		<FormLayoutGroup Caption="Почта администратора" ColSpan="2" Order="2">
			<FormLayoutItems>
				<FormLayoutItem Caption="Адрес почты" Enabled="true" Order="1">
					<BoundProperty>EmailAdminAddress</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
		<FormLayoutGroup Caption="Настройки почты системы" ColSpan="2" Order="3">
			<FormLayoutItems>
				<FormLayoutItem Caption="Адрес почты" Enabled="true" Order="1">
					<BoundProperty>EmailAddress</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Адрес сервера" Enabled="true" Order="2">
					<BoundProperty>EmailSmtpServer</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Порт сервера" Enabled="true" Order="3">
					<BoundProperty>EmailSmtpPort</BoundProperty>
					<NestedExtension>SpinEdit</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Учетная запись" Enabled="true" Order="4">
					<BoundProperty>EmailUserName</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Пароль почты" Enabled="true" Order="5">
					<BoundProperty>EmailPassword</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.Password</PropertiesChain>
							<Value>true</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Разрешить SSL" Enabled="true" Order="5">
					<BoundProperty>EmailEnableSsl</BoundProperty>
					<NestedExtension>CheckBox</NestedExtension>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
		<FormLayoutGroup Caption="Дополнительные настройки" ColSpan="2" Order="4">
			<FormLayoutItems>
				<FormLayoutItem Caption="Дополнительные настройки" Enabled="true" Order="1">
					<BoundProperty>CustomData</BoundProperty>
					<NestedExtension>Memo</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>CaptionSettings.Location</PropertiesChain>
							<Value>Top</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.ClientSideEvents.Init</PropertiesChain>
							<Value HasEscapedContent="true">
                function(sender, args)
                {
                  var inlineMemoEditorController = new Core.Admin.FormController.InlineMemoEditorController(sender, {mode:
                      {
                        name: "javascript",
                        json: true
                      }
                  });                  
                  inlineMemoEditorController.execute();                                    
                }
                </Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
	</FormLayoutGroups>
</FormLayout>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/Forms/DeviceReaderForm.xml
<FormLayout Name="measurementDeviceForm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FormLayout.xsd">
	<ColCount>2</ColCount>
	<ItemHeight>32</ItemHeight>
	<Width>500</Width>
	<InitScript HasEscapedContent="true">
      function (sender, args) 
      {
        jQuery(document).off(Core.Common.EventTypes.FormController.FormLoadComplete_Form);
        
        jQuery(document).on(Core.Common.EventTypes.FormController.FormLoadComplete_Form, function () 
          {
            var commandMenuBarController = new Core.Common.CommandMenuBarController("formCommandMenu");
                        
            var formController = Core.Admin.FormController.prototype.currentInstance;                 
            var entityTypeName = formController.getEntityTypeName();
                                   
            var doSendRequest = Core.Common.DeviceReaderResponseCommandDialog.prototype.sendRequestFromFormController;
            
            commandMenuBarController.bind(
            {   
              checkServiceStatus: function()
              {                                
                doSendRequest("checkServiceStatus", entityTypeName);
              },
              
              startService: function()
              {                                                              
                doSendRequest("startService", entityTypeName);
              },
              
              startServices: function()
              {                                                              
                doSendRequest("startServices", entityTypeName);
              },
              
              stopService: function()
              {                                                                
                doSendRequest("stopService", entityTypeName);
              },
              
              stopServices: function()
              {                                                                
                doSendRequest("stopServices", entityTypeName);
              } 
            });
          });
      }
    </InitScript>
	<CommandMenu>
		<Name>deviceReaderFormCommandMenu</Name>
		<ClientVisible>true</ClientVisible>
		<Width>125</Width>
		<CommandMenuItem>
			<Name>startServices</Name>
			<ToolTip>Запуск всех служб считывателей</ToolTip>
			<CommandName>startServices</CommandName>
			<IconClass>font-icon-start font-icon-darkgreen indent-right-5px</IconClass>
		</CommandMenuItem>
		<CommandMenuItem>
			<Name>stopServices</Name>
			<ToolTip>Останов всех служб считывателей</ToolTip>
			<CommandName>stopServices</CommandName>
			<IconClass>font-icon-stop font-icon-red indent-right-5px</IconClass>
		</CommandMenuItem>
		<CommandMenuItem>
			<Name>deviceReaderControl</Name>
			<DropDownMode>true</DropDownMode>
			<BeginGroup>true</BeginGroup>
			<CommandName>deviceReaderControl</CommandName>
			<IconClass>font-icon-checkconnection font-icon-color-darkred indent-right-5px</IconClass>
			<ToolTip>Управление службой считывателя устройств</ToolTip>
			<CommandMenuItem>
				<Name>startService</Name>
				<Text>Запуск службы считывателя...</Text>
				<CommandName>startService</CommandName>
				<IconClass>font-icon-start font-icon-darkgreen indent-right-5px</IconClass>
			</CommandMenuItem>
			<CommandMenuItem>
				<Name>stopService</Name>
				<Text>Останов службы считывателя...</Text>
				<CommandName>stopService</CommandName>
				<IconClass>font-icon-stop font-icon-red indent-right-5px</IconClass>
			</CommandMenuItem>
			<CommandMenuItem>
				<Name>checkServiceStatus</Name>
				<Text>Проверка состояния службы считывателя...</Text>
				<CommandName>checkServiceStatus</CommandName>
				<IconClass>font-icon-devicereader font-icon-black font-icon-x1_3 indent-right-5px</IconClass>
			</CommandMenuItem>
		</CommandMenuItem>
	</CommandMenu>
	<FormLayoutGroups>
		<FormLayoutGroup Caption="Идентифицирующие" ColSpan="2" Order="1">
			<FormLayoutItems>
				<FormLayoutItem Caption="Ид" Order="1" Enabled="false">
					<BoundProperty>Id</BoundProperty>
					<NestedExtension>SpinEdit</NestedExtension>
					<Tooltip>
						<HelpId>1</HelpId>
						<Text>Уникальный идентификатор сущности</Text>
					</Tooltip>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
							<Value>true</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Код" Order="2" Enabled="true">
					<BoundProperty>Code</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Наименование" Order="3" Enabled="true">
					<BoundProperty>Description</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Тип службы" Order="4" Enabled="true">
					<BoundProperty>DeviceReaderTypeId</BoundProperty>
					<NestedExtension>ComboBox</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
							<Value>Id</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
							<Value>Description</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
							<Value>{2}</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
		<FormLayoutGroup Caption="Настройки" ColSpan="1" Order="2">
			<FormLayoutItems>
				<FormLayoutItem Caption="IP-адрес SignalR" Order="1" Enabled="true">
					<BoundProperty>EditableSignalRNetAddress</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.MaskSettings.Mask</PropertiesChain>
							<Value>999.999.999.999</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.MaskSettings.IncludeLiterals</PropertiesChain>
							<Value>DecimalSymbol</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.ValidationSettings.Display</PropertiesChain>
							<Value>None</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Порт SignalR" Order="2" Enabled="true">
					<BoundProperty>SignalRPort</BoundProperty>
					<NestedExtension>SpinEdit</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Хаб SignalR" Order="3" Enabled="true">
					<BoundProperty>SignalRHub</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
		<FormLayoutGroup Caption="Взаимодействие с IIS" ColSpan="1" Order="3">
			<FormLayoutItems>
				<FormLayoutItem Caption="Адрес для коммуникаций" Order="1" Enabled="true">
					<BoundProperty>ServerCommunicatorNetAddress</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Учетная запись" Order="2" Enabled="true">
					<BoundProperty>UserId</BoundProperty>
					<NestedExtension>ButtonEdit</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
							<Value>true</Value>
						</FormLayoutItemExtender>
					  <FormLayoutItemExtender>
					    <PropertiesChain>NestedExtensionSettings.Properties.ClientSideEvents.Init</PropertiesChain>
					    <Value HasEscapedContent="true">
					      function(sender, args)
					      {
					        (new Core.Admin.FormController.LinkedEntityLookupDialog()).execute({sender: sender});
					      }
					    </Value>
					  </FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.Buttons.Add()</PropertiesChain>
							<Value></Value>
							<TypeName>System.Delegate</TypeName>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Контроллер" Order="3" Enabled="true">
					<BoundProperty>ServerCommunicatorController</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Действие" Order="4" Enabled="true">
					<BoundProperty>ServerCommunicatorReceiveAction</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
		<FormLayoutGroup Caption="Параметры опроса" ColSpan="2" Order="4">
			<FormLayoutItems>
				<FormLayoutItem Caption="Интервал обновления конфигурации (мин.)" Order="1" Enabled="true">
					<BoundProperty>UpdateConfigInterval</BoundProperty>
					<NestedExtension>SpinEdit</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Кол-во потоков опроса" Order="2" Enabled="true">
					<BoundProperty>MaxThreadCount</BoundProperty>
					<NestedExtension>SpinEdit</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Просмотр очереди (сек.)" Order="3" Enabled="true">
					<BoundProperty>QueuePollingInterval</BoundProperty>
					<NestedExtension>SpinEdit</NestedExtension>
				</FormLayoutItem>
				<FormLayoutItem Caption="Снятие зависших потоков (мин.)" Order="4" Enabled="true">
					<BoundProperty>HoveringTaskRemoveTime</BoundProperty>
					<NestedExtension>SpinEdit</NestedExtension>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
	</FormLayoutGroups>
</FormLayout>
