=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/Forms/FormLayout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:attribute default="false" name="HasEscapedContent" type="xs:boolean"/>
    <xs:element name="FormLayout">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ColCount" type="xs:unsignedInt"/>
                <xs:element name="ItemHeight" type="xs:unsignedInt"/>
                <xs:element name="Width" type="xs:unsignedInt"/>
                <xs:element maxOccurs="1" minOccurs="0" name="InitScript">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute ref="HasEscapedContent" use="optional"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="1" minOccurs="0" name="InitStyle" type="xs:string"/>
                <xs:element minOccurs="0" ref="CommandMenu"/>
                <xs:element name="FormLayoutGroups">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="FormLayoutGroup">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="FormLayoutItems">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded"
                                                  name="FormLayoutItem">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="BoundProperty"/>
                                                  <xs:element name="NestedExtension">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="TextBox"/>
                                                  <xs:enumeration value="SpinEdit"/>
                                                  <xs:enumeration value="TimeEdit"/>
                                                  <xs:enumeration value="TrackBar"/>
                                                  <xs:enumeration value="DateEdit"/>
                                                  <xs:enumeration value="CheckBox"/>
                                                  <xs:enumeration value="ButtonEdit"/>
                                                  <xs:enumeration value="Memo"/>
                                                  <xs:enumeration value="ComboBox"/>
                                                  <xs:enumeration value="ListBox"/>
                                                  <xs:enumeration value="Default"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element minOccurs="0" name="IsNotClonable"
                                                  type="xs:boolean"/>
                                                  <xs:element minOccurs="0" name="Tooltip">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element minOccurs="0" name="HelpId"
                                                  type="xs:int"/>
                                                  <xs:element minOccurs="1" name="Text"
                                                  type="xs:string"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element minOccurs="0"
                                                  name="FormLayoutItemExtenders">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded"
                                                  name="FormLayoutItemExtender">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="PropertiesChain"
                                                  type="xs:string"/>
                                                  <xs:element name="Value">
                                                  <xs:complexType>
                                                  <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute ref="HasEscapedContent"
                                                  use="optional"/>
                                                  </xs:extension>
                                                  </xs:simpleContent>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="TypeName" minOccurs="0">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="System.String"/>
                                                  <xs:enumeration value="System.Delegate"/>
                                                  <xs:enumeration value="System.Int32"/>
                                                  <xs:enumeration value="System.Boolean"/>
                                                  <xs:enumeration value="System.DateTime"/>
                                                  <xs:enumeration
                                                  value="DevExpress.Web.ASPxEditors.EditFormat"/>
                                                  <xs:enumeration
                                                  value="DevExpress.Web.ASPxEditors.Display"/>
                                                  <xs:enumeration
                                                  value="DevExpress.Web.ASPxEditors.MaskIncludeLiteralsMode"
                                                  />
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element minOccurs="0"
                                                  ref="FormLayoutItemListBoxSetting"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="Caption" type="xs:string"/>
                                                  <xs:attribute name="Order" type="xs:unsignedInt"/>
                                                  <xs:attribute name="Enabled" type="xs:boolean"/>
                                                  <xs:attribute name="ClientVisible"
                                                  type="xs:boolean" use="optional"/>
                                                  <xs:attribute name="IsGrid" type="xs:boolean"
                                                  use="optional"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="Caption" type="xs:string"/>
                                    <xs:attribute name="ColSpan" type="xs:unsignedInt"/>
                                    <xs:attribute name="Order" type="xs:unsignedInt"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="CommandMenuItem">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="CommandMenuItem"/>
                <xs:element name="AdditionalInfo" type="xs:string"/>
                <xs:element name="BeginGroup" type="xs:boolean"/>
                <xs:element name="CommandName" type="xs:string"/>
                <xs:element name="Enabled" type="xs:boolean"/>
                <xs:element name="IconClass" type="xs:string"/>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Text" type="xs:string"/>
                <xs:element name="ToolTip" type="xs:string"/>
                <xs:element maxOccurs="1" minOccurs="0" name="Checked" type="xs:boolean"/>
                <xs:element minOccurs="0" name="GroupName" type="xs:string"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="CommandMenu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="ClientVisible" type="xs:boolean"/>
                <xs:element maxOccurs="1" minOccurs="1" name="Width" type="xs:int"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="CommandMenuItem"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="FormLayoutItemListBoxSetting">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" name="DataSourceType">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Dictionary"/>
                            <xs:enumeration value="DictionaryWithAll"/>
                            <xs:enumeration value="DictionaryList"/>
                            <xs:enumeration value="DictionaryByQuery"/>
                            <xs:enumeration value="Entity"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="1" name="DataSource" type="xs:string"/>
                <xs:element minOccurs="0" name="DataSourceQuery" type="xs:string"/>
                <xs:element minOccurs="0" name="FormLayoutItemListBoxColumns">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="FormLayoutItemListBoxColumn">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="FieldName" type="xs:string"/>
                                        <xs:element name="Caption" type="xs:string"/>
                                        <xs:element minOccurs="0" name="Width" type="xs:int"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/Forms/OrganizationForm.xml
<FormLayout Name="organizationForm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FormLayout.xsd">
	<ColCount>2</ColCount>
	<ItemHeight>32</ItemHeight>
	<Width>500</Width>
	<FormLayoutGroups>
		<FormLayoutGroup Caption="Идентифицирующие" ColSpan="2" Order="1">
			<FormLayoutItems>
				<FormLayoutItem Caption="Ид" Enabled="false" Order="1">
					<BoundProperty>Id</BoundProperty>
					<NestedExtension>SpinEdit</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
							<Value>true</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Наименование" Order="2" Enabled="true">
					<BoundProperty>Description</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
							<Value>false</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Полный адрес" Enabled="true" Order="3">
					<BoundProperty>FullAddress</BoundProperty>
					<NestedExtension>ButtonEdit</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.Buttons.Add()</PropertiesChain>
							<Value></Value>
							<TypeName>System.Delegate</TypeName>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.Buttons.Add()</PropertiesChain>
							<Value></Value>
							<TypeName>System.Delegate</TypeName>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.ClientSideEvents.Init</PropertiesChain>
							<Value HasEscapedContent="true">
                function(sender, args)
                {
                  var context$ = jQuery(sender.GetMainElement());
                  jQuery(".dxeButton:last img", context$).hide();
                  jQuery(".dxeButton:first img", context$).hide();
                  jQuery(".dxeButton:last", context$).append(jQuery("&lt;i style=&apos;margin-right: 2px&apos; class=&apos;font-icon-google_maps&apos; title=&apos;Выбрать строение на карте&apos;&gt;&lt;/i&gt;;"));
                  jQuery(".dxeButton:first", context$).append(jQuery("&lt;i style=&apos;margin-right: 2px&apos; class=&apos;font-icon-building&apos; title=&apos;Редактировать адрес&apos;&gt;&lt;/i&gt;"));
                }        
                </Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.ClientSideEvents.ButtonClick</PropertiesChain>
							<Value HasEscapedContent="true">
                function(sender, args)
                {
                  var cusmomizer = Core.Admin.FormController.Customizer.prototype.currentInstance;
                  args["entityTypeName"] = "Organization";
                  switch(args.buttonIndex)
                  {
                    case 0:
                    {
                      cusmomizer.buttonEditShowBuildingAddressDialogHandler(sender, args);
                      break;
                    }
                    case 1:
                    {
                      cusmomizer.buttonEditShowMapDialogHandler(sender, args);
                      break;
                    }
                    default: break;
                  }
                }
                </Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
							<Value>true</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Геолокация" ClientVisible="false" Enabled="true" Order="4">
					<BoundProperty>Geolocation</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
							<Value>true</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
		<FormLayoutGroup Caption="Назначение" ColSpan="2" Order="2">
			<FormLayoutItems>
				<FormLayoutItem Caption="Тип организации" Enabled="true" Order="1">
					<BoundProperty>OrganizationTypeId</BoundProperty>
					<NestedExtension>ComboBox</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
							<Value>Id</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
							<Value>Description</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
							<Value>{2}</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
	</FormLayoutGroups>
</FormLayout>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/Forms/ChannelTemplateForm.xml
<FormLayout Name="channelTemplateForm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FormLayout.xsd">
	<ColCount>2</ColCount>
	<ItemHeight>32</ItemHeight>
	<Width>500</Width>
	<InitScript HasEscapedContent="true">
    function(sender, args)
	  {	    
	    var inlineGridController = new Core.Admin.FormController.InlineGridController(
	    {
	      rightEntityTypeName: Core.Common.Entities.Business.ParameterMapDeviceParameter
	    });
	    inlineGridController.execute();
	  }
  </InitScript>
	<FormLayoutGroups>
		<FormLayoutGroup Caption="Идентифицирующие" ColSpan="2" Order="1">
			<FormLayoutItems>
				<FormLayoutItem Caption="Ид" Enabled="false" Order="1">
					<BoundProperty>Id</BoundProperty>
					<NestedExtension>SpinEdit</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
							<Value>true</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Наименование" Order="2" Enabled="true">
					<BoundProperty>Description</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
							<Value>true</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
		<FormLayoutGroup Caption="Основные" ColSpan="1" Order="1">
			<FormLayoutItems>
				<FormLayoutItem Caption="Тип ресурсной системы" Enabled="true" Order="1">
					<BoundProperty>ResourceSystemTypeId</BoundProperty>
					<NestedExtension>ComboBox</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
							<Value>Id</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
							<Value>Description</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
							<Value>{2}</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Подтип ресурсной системы" Enabled="true" Order="2">
					<BoundProperty>ResourceSubsystemTypeId</BoundProperty>
					<NestedExtension>ComboBox</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
							<Value>Id</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
							<Value>Description</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
							<Value>{2}</Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Модель прибора" Enabled="true" Order="3">
					<BoundProperty>DeviceId</BoundProperty>
					<NestedExtension>ButtonEdit</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
							<Value>true</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.ClientSideEvents.Init</PropertiesChain>
							<Value HasEscapedContent="true">
                function(sender, args)
                {                 
                  (new Core.Admin.FormController.LinkedEntityLookupDialog()).execute(
                    {
                      sender: sender                      
                    }
                  );
                }
                </Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.Buttons.Add()</PropertiesChain>
							<Value></Value>
							<TypeName>System.Delegate</TypeName>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
		<FormLayoutGroup Caption="Дополнительные" ColSpan="1" Order="2">
			<FormLayoutItems>
				<FormLayoutItem Caption="Мнемосхема" Order="3" Enabled="true">
					<BoundProperty>MnemoschemeId</BoundProperty>
					<NestedExtension>ButtonEdit</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
							<Value>true</Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.Buttons.Add()</PropertiesChain>
							<Value></Value>
							<TypeName>System.Delegate</TypeName>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.Buttons.Add()</PropertiesChain>
							<Value></Value>
							<TypeName>System.Delegate</TypeName>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.ClientSideEvents.ButtonClick</PropertiesChain>
							<Value HasEscapedContent="true">
                function(sender, args)
                {
                  var customizer = Core.Admin.FormController.Customizer.prototype.currentInstance;
                  if(args.buttonIndex === 1)
                  {                    
                    customizer.buttonEditShowMnemoschemeImageDialogHandler(sender, args);
                  }
                }
                </Value>
						</FormLayoutItemExtender>
						<FormLayoutItemExtender>
							<PropertiesChain>NestedExtensionSettings.Properties.ClientSideEvents.Init</PropertiesChain>
							<Value HasEscapedContent="true">
                function(sender, args)
                {
                  var context$ = jQuery(sender.GetMainElement());
                  jQuery(".dxeButton:last img", context$).hide();
                  jQuery(".dxeButton:last", context$)
                  .append(jQuery("&lt;i style=&apos;margin-right: 2px&apos; class=&apos;font-icon-picture&apos;&gt;&lt;/i&gt;"));
                  
                  (new Core.Admin.FormController.LinkedEntityLookupDialog()).execute(
                    {
                      sender: sender, 
                      buttonIndex: Number.zero
                    }
                  );
                }
                </Value>
						</FormLayoutItemExtender>
					</FormLayoutItemExtenders>
				</FormLayoutItem>
				<FormLayoutItem Caption="Комментарий" Order="4" Enabled="true">
					<BoundProperty>Comment</BoundProperty>
					<NestedExtension>TextBox</NestedExtension>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
		<FormLayoutGroup Caption="Связи" ColSpan="2" Order="7">
			<FormLayoutItems>
				<FormLayoutItem Caption="Связь предметного параметра" Enabled="true" Order="1" IsGrid="true">
					<BoundProperty>ParameterMapDeviceParameters</BoundProperty>
					<NestedExtension>Default</NestedExtension>
					<FormLayoutItemExtenders>
						<FormLayoutItemExtender>
							<PropertiesChain>CaptionSettings.Location</PropertiesChain>
							<Value>Top</Value>
						</FormLayoutItemExtender>
            
					</FormLayoutItemExtenders>
				</FormLayoutItem>
			</FormLayoutItems>
		</FormLayoutGroup>
	</FormLayoutGroups>
</FormLayout>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/Forms/AgreementParameter.xml
<FormLayout Name="accessPointForm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="FormLayout.xsd">
  <ColCount>2</ColCount>
  <ItemHeight>32</ItemHeight>
  <Width>500</Width>
  <FormLayoutGroups>
    <FormLayoutGroup Caption="Идентифицирующие" ColSpan="2" Order="1">
      <FormLayoutItems>
        <FormLayoutItem Caption="Ид" Enabled="false" Order="1">
          <BoundProperty>Id</BoundProperty>
          <NestedExtension>SpinEdit</NestedExtension>
          <FormLayoutItemExtenders>
            <FormLayoutItemExtender>
              <PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
              <Value>true</Value>
            </FormLayoutItemExtender>
          </FormLayoutItemExtenders>
        </FormLayoutItem>
        <FormLayoutItem Caption="Наименование" Order="2" Enabled="true">
          <BoundProperty>Description</BoundProperty>
          <NestedExtension>TextBox</NestedExtension>
          <FormLayoutItemExtenders>
            <FormLayoutItemExtender>
              <PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
              <Value>true</Value>
            </FormLayoutItemExtender>
          </FormLayoutItemExtenders>
        </FormLayoutItem>
      </FormLayoutItems>
    </FormLayoutGroup>
    <FormLayoutGroup Caption="Основные" ColSpan="2" Order="2">
      <FormLayoutItems>
        <FormLayoutItem Caption="Тип договорного параметра" Enabled="true" Order="1">
          <BoundProperty>AgreementParameterTypeId</BoundProperty>
          <NestedExtension>ComboBox</NestedExtension>
          <FormLayoutItemExtenders>
            <FormLayoutItemExtender>
              <PropertiesChain>NestedExtensionSettings.Properties.ValueField</PropertiesChain>
              <Value>Id</Value>
            </FormLayoutItemExtender>
            <FormLayoutItemExtender>
              <PropertiesChain>NestedExtensionSettings.Properties.TextField</PropertiesChain>
              <Value>Description</Value>
            </FormLayoutItemExtender>
            <FormLayoutItemExtender>
              <PropertiesChain>NestedExtensionSettings.Properties.TextFormatString</PropertiesChain>
              <Value>{2}</Value>
            </FormLayoutItemExtender>
            <FormLayoutItemExtender>
              <PropertiesChain>NestedExtensionSettings.ReadOnly</PropertiesChain>
              <Value>false</Value>
            </FormLayoutItemExtender>
          </FormLayoutItemExtenders>
        </FormLayoutItem>
        <FormLayoutItem Caption="Значение" Order="2" Enabled="true">
          <BoundProperty>Value</BoundProperty>
          <NestedExtension>TextBox</NestedExtension>
        </FormLayoutItem>
      </FormLayoutItems>
    </FormLayoutGroup>
  </FormLayoutGroups>
</FormLayout>
