=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/EntityTrees/EntityTree.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="EntityTreeRoot">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Title" type="xs:string"/>
        <xs:element name="EntityTypeName" type="xs:string"/>
        <xs:element minOccurs="0" name="InjectedCss" type="xs:string"/>
        <xs:element minOccurs="0" name="IconClass" type="xs:string"/>
        <xs:element name="Visible" type="xs:boolean" minOccurs="1"/>
        <xs:element minOccurs="0" ref="PropertyCustomizerExpression"/>
        <xs:element minOccurs="0" name="EntityTreeDictionaries">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="EntityTreeDictionary" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="EntityTreeInverseProperties">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="EntityTreeInverseProperty"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="EntityTreeNodes">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element maxOccurs="unbounded" minOccurs="0" ref="EntityTreeNode"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Script">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Id" type="xs:integer"/>
        <xs:element minOccurs="0" name="Code" nillable="true" type="xs:string"/>
        <xs:element minOccurs="0" name="Description" nillable="true" type="xs:string"/>
        <xs:element minOccurs="0" name="Language" type="xs:string"/>
        <xs:element minOccurs="0" name="Template" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PropertyCustomizerExpression">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="Expression" type="xs:string"/>
        <xs:element minOccurs="0" ref="Script"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="EntityTreeNodeCollectionSorterInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="KeySelectorExpression" type="xs:string"/>
        <xs:element name="KeySelectorType">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="String"/>
              <xs:enumeration value="Int32"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Ascending" type="xs:boolean"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="EntityTreeNode">
    <xs:complexType>
      <xs:sequence maxOccurs="1" minOccurs="1">
        <xs:element name="EntityTypeName" type="xs:string"/>
        <xs:element name="Property" type="xs:string"/>
        <xs:element maxOccurs="1" minOccurs="0" ref="EntityTreeNodeCollectionSorterInfo"/>
        <xs:element minOccurs="0" name="CustomPropertyChain" type="xs:string"/>
        <xs:element minOccurs="0" name="IconClass" type="xs:string"/>
        <xs:element name="Visible" type="xs:boolean"/>
        <xs:element minOccurs="0" ref="PropertyCustomizerExpression"/>
        <xs:element minOccurs="0" name="EntityTreeNodes">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element maxOccurs="unbounded" minOccurs="0" ref="EntityTreeNode"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/EntityTrees/EntityTree5.xml
<EntityTreeRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EntityTree.xsd">
  <Title>Точки доступа</Title>
  <EntityTypeName>AccessPoint</EntityTypeName>
  
  <IconClass>et-ap</IconClass>
  <Visible>false</Visible>
  <Script>
    <Id>5</Id>
  </Script>  
  <EntityTreeInverseProperties>    
    <EntityTreeInverseProperty>UserLinksChannel.User</EntityTreeInverseProperty>
    <EntityTreeInverseProperty>Placement.PlacementPurpose</EntityTreeInverseProperty>
    <EntityTreeInverseProperty>Placement.Building.AccessPointLinksBuilding.AccessPoint</EntityTreeInverseProperty>
  </EntityTreeInverseProperties>
  <EntityTreeNodes>
    <EntityTreeNode>
      <EntityTypeName>AccessPointLinkBuilding</EntityTypeName>
      <Property>AccessPointLinksBuilding</Property>      
      <Visible>false</Visible>
      <EntityTreeNodes>
        <EntityTreeNode>
          <EntityTypeName>Building</EntityTypeName>
          <Property>Building</Property>          
          <IconClass>et-b</IconClass>
          <Visible>true</Visible>
          <EntityTreeNodes>
            <EntityTreeNode >
              <EntityTypeName>Placement</EntityTypeName>
              <Property>Placements</Property>
              <CustomPropertyChain>Placements.PlacementPurpose</CustomPropertyChain>              
              <IconClass>et-pl</IconClass>
              <Visible>true</Visible>
              <EntityTreeNodes>
                <EntityTreeNode>
                  <EntityTypeName>Channel</EntityTypeName>
                  <Property>Channels</Property>                                    
                  <Visible>false</Visible>
                  <EntityTreeNodes>
                    <EntityTreeNode>
                      <EntityTypeName>MeasurementDevice</EntityTypeName>
                      <Property>MeasurementDevice</Property>                                      
                      <IconClass>et-md</IconClass>
                      <Visible>true</Visible>
                    </EntityTreeNode>                    
                  </EntityTreeNodes>
                </EntityTreeNode>
              </EntityTreeNodes>
            </EntityTreeNode>
          </EntityTreeNodes>
        </EntityTreeNode>
      </EntityTreeNodes>
    </EntityTreeNode>
  </EntityTreeNodes>
</EntityTreeRoot>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/EntityTrees/EntityTree4.xml
<EntityTreeRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EntityTree.xsd">
  <Title>Строения</Title>
  <EntityTypeName>Building</EntityTypeName>
  <IconClass>et-b</IconClass>
  <Visible>false</Visible>
  <Script>
    <Id>4</Id>
  </Script>
  <EntityTreeInverseProperties>    
    <EntityTreeInverseProperty>UserLinksChannel.User</EntityTreeInverseProperty>
    <EntityTreeInverseProperty>AccessPoint.AccessPointLinksBuilding.Building.Placements.PlacementPurpose</EntityTreeInverseProperty>
      <EntityTreeInverseProperty>AccessPoint.AccessPointLinksBuilding.Building.Placements.Channels</EntityTreeInverseProperty>
    <EntityTreeInverseProperty>AccessPoint.AccessPointLinksBuilding.Building.Placements.UserAdditionalInfo</EntityTreeInverseProperty>
    <EntityTreeInverseProperty>AccessPoint.AccessPointLinksBuilding.Building.ResourceSystems</EntityTreeInverseProperty>
  </EntityTreeInverseProperties>
  <EntityTreeNodes>
    <EntityTreeNode>
      <EntityTypeName>AccessPointLinkBuilding</EntityTypeName>
      <Property>AccessPointLinksBuilding</Property>      
      <Visible>false</Visible>
      <EntityTreeNodes>
        <EntityTreeNode>
          <EntityTypeName>AccessPoint</EntityTypeName>
          <Property>AccessPoint</Property>
          <IconClass>et-ap</IconClass>          
          <Visible>true</Visible>
          <EntityTreeNodes>
            <EntityTreeNode>
              <EntityTypeName>MeasurementDevice</EntityTypeName>
              <Property>MeasurementDevices</Property>                            
              <IconClass>et-md</IconClass>
              <Visible>true</Visible>
            </EntityTreeNode>            
          </EntityTreeNodes>
        </EntityTreeNode>
      </EntityTreeNodes>
    </EntityTreeNode>
    <EntityTreeNode >
      <EntityTypeName>Placement</EntityTypeName>
      <Property>Placements</Property>
      <CustomPropertyChain>Placements.PlacementPurpose</CustomPropertyChain>
      <IconClass>et-pl</IconClass>
      <Visible>true</Visible>
      <EntityTreeNodes>
        <EntityTreeNode>
          <EntityTypeName>Channel</EntityTypeName>
          <Property>Channels</Property>                    
          <Visible>false</Visible>
          <EntityTreeNodes>
            <EntityTreeNode>
              <EntityTypeName>MeasurementDevice</EntityTypeName>
              <Property>MeasurementDevice</Property>                           
              <IconClass>et-md</IconClass>
              <Visible>true</Visible>
            </EntityTreeNode>
          </EntityTreeNodes>
        </EntityTreeNode>
        <EntityTreeNode>
          <EntityTypeName>UserAdditionalInfo</EntityTypeName>
          <Property>UserAdditionalInfo</Property>          
          <IconClass>et-uai</IconClass>
          <Visible>true</Visible>
          <EntityTreeNodes>
            <EntityTreeNode>
              <EntityTypeName>User</EntityTypeName>
              <Property>User</Property>              
              <IconClass>et-us</IconClass>
              <Visible>true</Visible>
            </EntityTreeNode>
          </EntityTreeNodes>
        </EntityTreeNode>
      </EntityTreeNodes>
    </EntityTreeNode>    
  </EntityTreeNodes>
</EntityTreeRoot>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/EntityTrees/EntityTree3.xml
<EntityTreeRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EntityTree.xsd">
  <Title>Строения</Title>
  <EntityTypeName>Building</EntityTypeName>
  <IconClass>et-b</IconClass>
  <Visible>false</Visible>
  <Script>
    <Id>3</Id>
  </Script>
  <EntityTreeNodes>
    <EntityTreeNode >
      <EntityTypeName>Placement</EntityTypeName>
      <Property>Placements</Property>
      <CustomPropertyChain>Placements.PlacementPurpose</CustomPropertyChain>      
      <IconClass>et-pl</IconClass>
      <Visible>true</Visible>
      <EntityTreeNodes>
        <EntityTreeNode>
          <EntityTypeName>UserAdditionalInfo</EntityTypeName>
          <Property>UserAdditionalInfo</Property>          
          <IconClass>et-uai</IconClass>
          <Visible>true</Visible>
          <EntityTreeNodes>
            <EntityTreeNode>
              <EntityTypeName>User</EntityTypeName>
              <Property>User</Property>                            
              <IconClass>et-us</IconClass>
              <Visible>true</Visible>
            </EntityTreeNode>
          </EntityTreeNodes>
        </EntityTreeNode>
      </EntityTreeNodes>
    </EntityTreeNode>
  </EntityTreeNodes>
</EntityTreeRoot>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/EntityTrees/EntityTree7.xml
<EntityTreeRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EntityTree.xsd">
  <Title>Города</Title>
  <EntityTypeName>City</EntityTypeName>
  <IconClass>et-ci</IconClass>
  <Visible>false</Visible>
  <Script>
    <Id>7</Id>
  </Script>
  
  <EntityTreeDictionaries>
    <EntityTreeDictionary>ResourceSystemType</EntityTreeDictionary>
    <EntityTreeDictionary>PlacementPurpose</EntityTreeDictionary>
  </EntityTreeDictionaries>
  <EntityTreeInverseProperties>
    <EntityTreeInverseProperty>UserLinksChannel.User</EntityTreeInverseProperty>
    <EntityTreeInverseProperty>Placement.Building.District.City</EntityTreeInverseProperty>
  </EntityTreeInverseProperties>

  <EntityTreeNodes>
    <EntityTreeNode>
      <EntityTypeName>District</EntityTypeName>
      <Property>Districts</Property>
      <EntityTreeNodeCollectionSorterInfo>
        <KeySelectorExpression>objNode.Description</KeySelectorExpression>
        <KeySelectorType>String</KeySelectorType>
        <Ascending>true</Ascending>
      </EntityTreeNodeCollectionSorterInfo>      
      <IconClass>et-di</IconClass>                       
      <Visible>true</Visible>
      
      <EntityTreeNodes>
        <EntityTreeNode>
          <EntityTypeName>Building</EntityTypeName>
          <Property>Buildings</Property>
          <EntityTreeNodeCollectionSorterInfo>
            <KeySelectorExpression>Regex.Replace(objNode.Description, &quot;(улица|ул\\.|проспект|пр\\.|\\s+улица)&quot;, String.Empty).Trim()</KeySelectorExpression>
            <KeySelectorType>String</KeySelectorType>
            <Ascending>true</Ascending>
          </EntityTreeNodeCollectionSorterInfo>          
          <IconClass>et-b</IconClass>
          <Visible>true</Visible>
          
          <EntityTreeNodes>
            <EntityTreeNode >
              <EntityTypeName>Placement</EntityTypeName>
              <Property>Placements</Property>
              <CustomPropertyChain>Placements.PlacementPurpose</CustomPropertyChain>              
              <Visible>false</Visible>
              
              <EntityTreeNodes>
                <EntityTreeNode>
                  <EntityTypeName>Channel</EntityTypeName>
                  <Property>Channels</Property>                  
                  <EntityTreeNodeCollectionSorterInfo>
                    <KeySelectorExpression>objNode.Order</KeySelectorExpression>
                    <KeySelectorType>Int32</KeySelectorType>
                    <Ascending>true</Ascending>
                  </EntityTreeNodeCollectionSorterInfo>                  
                  <CustomPropertyChain>Channels.ResourceSystemType</CustomPropertyChain>                  
                  <IconClass>et-ch</IconClass>
                  <Visible>true</Visible>
                </EntityTreeNode>
              </EntityTreeNodes>
            </EntityTreeNode>
          </EntityTreeNodes>
        </EntityTreeNode>
      </EntityTreeNodes>
    </EntityTreeNode>
  </EntityTreeNodes>
</EntityTreeRoot>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/EntityTrees/EntityTree6.xml
<EntityTreeRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EntityTree.xsd">
  <Title>Строения</Title>
  <EntityTypeName>Building</EntityTypeName>
  
  <IconClass>et-b</IconClass>
  <Visible>false</Visible>
  <Script>
    <Id>6</Id>
  </Script>
  <EntityTreeInverseProperties>    
    <EntityTreeInverseProperty>UserLinksChannel.User</EntityTreeInverseProperty>
    <EntityTreeInverseProperty>Placement.PlacementPurpose</EntityTreeInverseProperty>    
  </EntityTreeInverseProperties>
  <EntityTreeNodes>
    <EntityTreeNode >
      <EntityTypeName>Placement</EntityTypeName>
      <Property>Placements</Property>
      <CustomPropertyChain>Placements.PlacementPurpose</CustomPropertyChain>
      <IconClass>et-pl</IconClass>
      <Visible>true</Visible>
      <EntityTreeNodes>
        <EntityTreeNode>
          <EntityTypeName>Channel</EntityTypeName>
          <Property>Channels</Property>                    
          <Visible>false</Visible>
          <EntityTreeNodes>
            <EntityTreeNode>
              <EntityTypeName>MeasurementDevice</EntityTypeName>
              <Property>MeasurementDevice</Property>              
              <IconClass>et-md</IconClass>
              <Visible>true</Visible>
            </EntityTreeNode>
          </EntityTreeNodes>
        </EntityTreeNode>
      </EntityTreeNodes>
    </EntityTreeNode>
    
  </EntityTreeNodes>
</EntityTreeRoot>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/EntityTrees/EntityTree8.xml
<EntityTreeRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EntityTree.xsd">
  <Title>Организации</Title>
  <EntityTypeName>Organization</EntityTypeName>
  <IconClass>et-or</IconClass>
  <Visible>false</Visible>
  <Script>
    <Id>8</Id>
  </Script>
  <EntityTreeDictionaries>
    <EntityTreeDictionary>ResourceSystemType</EntityTreeDictionary>
    <EntityTreeDictionary>PlacementPurpose</EntityTreeDictionary>
  </EntityTreeDictionaries>
  <EntityTreeInverseProperties>
    <EntityTreeInverseProperty>UserLinksChannel.User</EntityTreeInverseProperty>
    <EntityTreeInverseProperty>Placement.Building.District.City</EntityTreeInverseProperty>
    <EntityTreeInverseProperty>Placement.Building.Organization</EntityTreeInverseProperty>
  </EntityTreeInverseProperties>
  <EntityTreeNodes>
    <EntityTreeNode>
      <EntityTypeName>Building</EntityTypeName>
      <Property>Buildings</Property>
      <EntityTreeNodeCollectionSorterInfo>
        <KeySelectorExpression>Regex.Replace(objNode.Description, &quot;(улица|ул\\.|проспект|пр\\.|\\s+улица)&quot;, String.Empty).Trim()</KeySelectorExpression>
        <KeySelectorType>String</KeySelectorType>
        <Ascending>true</Ascending>
      </EntityTreeNodeCollectionSorterInfo>      
      <IconClass>et-b</IconClass>
      <Visible>true</Visible>
      <EntityTreeNodes>
        <EntityTreeNode >
          <EntityTypeName>Placement</EntityTypeName>
          <Property>Placements</Property>
          <CustomPropertyChain>Placements.PlacementPurpose</CustomPropertyChain>          
          <IconClass>et-pl</IconClass>
          <Visible>true</Visible>          
          <EntityTreeNodes>
            <EntityTreeNode>
              <EntityTypeName>Channel</EntityTypeName>
              <Property>Channels</Property>
              <CustomPropertyChain>Channels.ResourceSystemType</CustomPropertyChain>
              <IconClass>et-ch</IconClass>
              <Visible>true</Visible>
            </EntityTreeNode>
          </EntityTreeNodes>
        </EntityTreeNode>
      </EntityTreeNodes>
    </EntityTreeNode>
  </EntityTreeNodes>
</EntityTreeRoot>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/EntityTrees/EntityTree2.xml
<EntityTreeRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EntityTree.xsd">
  <Title>Строения</Title>
  <EntityTypeName>Building</EntityTypeName>  
  <IconClass>et-b</IconClass>
  <Visible>false</Visible>
  <Script>
    <Id>2</Id>
  </Script>
  <EntityTreeInverseProperties>    
    <EntityTreeInverseProperty>UserLinksChannel.User</EntityTreeInverseProperty>
    <EntityTreeInverseProperty>AccessPoint.AccessPointLinksBuilding.Building</EntityTreeInverseProperty>
  </EntityTreeInverseProperties>
  <EntityTreeNodes>
    <EntityTreeNode>
      <EntityTypeName>AccessPointLinkBuilding</EntityTypeName>
      <Property>AccessPointLinksBuilding</Property>      
      <Visible>false</Visible>
      <EntityTreeNodes>        
        <EntityTreeNode>
          <EntityTypeName>AccessPoint</EntityTypeName>
          <Property>AccessPoint</Property>          
          <IconClass>et-ap</IconClass>
          <Visible>true</Visible>
          
          <EntityTreeNodes>
            <EntityTreeNode>
              <EntityTypeName>MeasurementDevice</EntityTypeName>
              <Property>MeasurementDevices</Property>                       
              <IconClass>et-md</IconClass>              
              <Visible>true</Visible>
                           
            </EntityTreeNode>            
          </EntityTreeNodes>
        </EntityTreeNode>
      </EntityTreeNodes>
    </EntityTreeNode>
  </EntityTreeNodes>
</EntityTreeRoot>
