=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/CommandMenu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="CommandMenuItem">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element ref="CommandMenuItem"/>
        <xs:element name="Name" type="xs:string"/>
        <xs:element name="AdditionalInfo" type="xs:string"/>
        <xs:element name="BeginGroup" type="xs:boolean"/>
        <xs:element name="CommandName" type="xs:string"/>
        <xs:element name="Enabled" type="xs:boolean" minOccurs="0"/>
        <xs:element minOccurs="0" name="Visible" type="xs:boolean"/>
        <xs:element name="IconClass" type="xs:string" minOccurs="0"/>
        <xs:element name="DropDownMode" type="xs:boolean" minOccurs="0"/>
        <xs:element name="TryMergeByName" type="xs:boolean" minOccurs="0"/>
        <xs:element name="Text" type="xs:string"/>
        <xs:element name="ToolTip" type="xs:string"/>
        <xs:element name="Checked" type="xs:boolean" minOccurs="0"/>
        <xs:element name="GroupName" type="xs:string" minOccurs="0"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="CommandMenu">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:string"/>
        <xs:element name="ClientVisible" type="xs:boolean"/>
        <xs:element maxOccurs="1" minOccurs="1" name="Width" type="xs:int"/>
        <xs:element name="EnableAdaptivity" type="xs:boolean"/>

        <xs:element maxOccurs="unbounded" minOccurs="0" ref="CommandMenuItem"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/FlatHolderDashboardCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>flatHolderDashboardCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>250</Width>
  <CommandMenuItem>
    <Name>refresh</Name>
    <CommandName>refresh</CommandName>
    <ToolTip>Обновить содержимое</ToolTip>
    <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>showOptions</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <ToolTip>Настройки</ToolTip>
    <CommandName>showOptions</CommandName>
    <Text></Text>
    <IconClass>font-icon-options font-icon-x1_2 font-icon-darkslateblue indent-right-5px</IconClass>

    <CommandMenuItem>
      <Name>showInterval</Name>
      <Text>Временной интервал...</Text>
      <CommandName>showInterval</CommandName>
      <IconClass>font-icon-interval font-icon-x1_3 font-icon-black indent-right-5px</IconClass>
    </CommandMenuItem>

  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>showArchiveJournal</Name>
    <CommandName>showArchiveJournal</CommandName>
    <AdditionalInfo>Archive</AdditionalInfo>
    <ToolTip>Журнал архивов устройства</ToolTip>
    <IconClass>font-icon-archive font-icon-x1_2 font-icon-orangered</IconClass>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>checkConnection</Name>
    <ToolTip>Проверка связи с устройством...</ToolTip>
    <CommandName>checkConnection</CommandName>
    <IconClass>font-icon-checkconnection font-icon-x1_3 font-icon-color-darkred indent-right-5px</IconClass>
  </CommandMenuItem>

</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/DashboardDiagrammDialogContextCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>dashboardDiagrammDialogContextCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>220</Width>
  
  <CommandMenuItem>
    <Name>argumentAxisLabelToggle</Name>
    <Text>Показать подпись оси X</Text>
    <CommandName>argumentAxisLabelToggle</CommandName>
    <Checked>false</Checked>
    <GroupName>argumentAxisLabelToggleGroup</GroupName>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>tooltipEnabledToggle</Name>
    <Text>Показать подсказку</Text>
    <CommandName>tooltipEnabledToggle</CommandName>
    <Checked>false</Checked>
    <GroupName>tooltipEnabledToggleGroup</GroupName>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>drillDownCumulativeTotal</Name>
    <Text>Разворачивать итоги</Text>
    <CommandName>drillDownCumulativeTotal</CommandName>
    <Checked>false</Checked>
    <GroupName>drillDownCumulativeTotal</GroupName>
  </CommandMenuItem>

</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/FormJournalDialogServerTimeEntityCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>formJournalDialogServerTimeEntityCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>250</Width>
  
  <CommandMenuItem>
    <Name>refresh</Name>
    <CommandName>refresh</CommandName>
    <ToolTip>Обновить содержимое</ToolTip>
    <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>formJournalExport</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>gridExport</CommandName>
    <IconClass>font-icon-file_export font-icon-x1_2 font-icon-darkslateblue</IconClass>
    <ToolTip>Экспорт</ToolTip>

    <CommandMenuItem>
      <Text>Формат Xlsx</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Xlsx</AdditionalInfo>
      <IconClass>font-icon-xlsx indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <CommandMenuItem>
      <Text>За интервал времени...</Text>
      <BeginGroup>true</BeginGroup>
      <CommandName>applyServerTimeEntityCustomFilter</CommandName>
      <Name>forCustomInterval</Name>
      <IconClass>font-icon-interval font-icon-x1_3 font-icon-black</IconClass>
    </CommandMenuItem>
    
    <Name>gridServerTimeEntityFilter</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>gridServerTimeEntityFilter</CommandName>
    <IconClass>font-icon-journalfilter font-icon-x1_3 indent-right-20px font-icon-darkgreen</IconClass>
    <ToolTip>Фильтр</ToolTip>
    <Text>Фильтр</Text>
    
    <CommandMenuItem>      
      <Text>За последний час</Text>      
      <BeginGroup>true</BeginGroup>      
      <CommandName>applyServerTimeEntityFilter</CommandName>
      <Name>forOneHour</Name>
      <IconClass>font-icon-onehour font-icon-x1_3 font-icon-greenyellow</IconClass>
      <AdditionalInfo>60</AdditionalInfo>
    </CommandMenuItem>

    <CommandMenuItem>
      <Text>За прошедшие 12 часов</Text>
      <BeginGroup>true</BeginGroup>
      <CommandName>applyServerTimeEntityFilter</CommandName>
      <Name>forTwentyHours</Name>
      <IconClass>font-icon-twentyhours font-icon-x1_3 font-icon-darkgreen</IconClass>
      <AdditionalInfo>720</AdditionalInfo>
    </CommandMenuItem>

    <CommandMenuItem>
      <Text>За прошедшие сутки</Text>
      <BeginGroup>true</BeginGroup>
      <CommandName>applyServerTimeEntityFilter</CommandName>
      <Name>forOneDay</Name>
      <IconClass>font-icon-oneday font-icon-x1_3 font-icon-orangered</IconClass>
      <AdditionalInfo>1440</AdditionalInfo>
    </CommandMenuItem>
    
    <CommandMenuItem>
      <Text>За прошедшую неделю</Text>
      <BeginGroup>true</BeginGroup>
      <CommandName>applyServerTimeEntityFilter</CommandName>
      <Name>forOneWeek</Name>
      <IconClass>font-icon-oneweek font-icon-x1_3 font-icon-brown</IconClass>
      <AdditionalInfo>10080</AdditionalInfo>
    </CommandMenuItem>
    
    <CommandMenuItem>
      <Text>За прошедший месяц</Text>
      <BeginGroup>true</BeginGroup>
      <CommandName>applyServerTimeEntityFilter</CommandName>
      <Name>forOneMonth</Name>
      <IconClass>font-icon-onemonth font-icon-x1_3 font-icon-red</IconClass>
      <AdditionalInfo>43200</AdditionalInfo>
    </CommandMenuItem>    
  </CommandMenuItem>

  <CommandMenuItem>
    <Text></Text>
    <CommandName>toggleCollapse</CommandName>
    <Name>toggleCollapse</Name>
    <ToolTip>Свернуть/развернуть окно</ToolTip>
    <IconClass>font-icon-toggle-collapsed font-icon-collapsed font-icon-darkgreen font-icon-x1_3</IconClass>
  </CommandMenuItem>
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/AdminLayoutHeaderCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>adminLayoutHeaderCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>115</Width>
  <CommandMenuItem>
    <Name>gotoStartPage</Name>
    <Text>
    </Text>
    <CommandName>gotoStartPage</CommandName>
    <ToolTip>К стартовой странице</ToolTip>
    <IconClass>font-icon-home font-icon-dimgray font-icon-x1_1</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>gotoBackward</Name>
    <Text>
    </Text>
    <CommandName>gotoBackward</CommandName>
    <ToolTip>К предыдущей странице</ToolTip>
    <IconClass>font-icon-left font-icon-dimgray font-icon-x1_1</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>gotoForward</Name>
    <Text>
    </Text>
    <CommandName>gotoForward</CommandName>
    <ToolTip>К следующей странице</ToolTip>
    <IconClass>font-icon-right font-icon-dimgray font-icon-x1_1</IconClass>
  </CommandMenuItem>
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/FormJournalDialogCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>formJournalDialogCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>250</Width>
  
  <CommandMenuItem>
    <Name>refresh</Name>
    <CommandName>refresh</CommandName>
    <ToolTip>Обновить содержимое</ToolTip>
    <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>formJournalExport</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>gridExport</CommandName>
    <IconClass>font-icon-file_export font-icon-x1_2 font-icon-darkslateblue</IconClass>
    <ToolTip>Экспорт</ToolTip>

    <CommandMenuItem>
      <Text>Формат Xlsx</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Xlsx</AdditionalInfo>
      <IconClass>font-icon-xlsx indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>setForcefullyHoldOnDialog</Name>
    <CommandName>setForcefullyHoldOnDialog</CommandName>    
    <ToolTip>Удерживать на форме</ToolTip>
    <IconClass>font-icon-toggle-pin font-icon-unpin font-icon-darkblue font-icon-x1_3</IconClass>
    <Visible>false</Visible>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Text></Text>
    <CommandName>toggleCollapse</CommandName>
    <Name>toggleCollapse</Name>
    <ToolTip>Свернуть/развернуть окно</ToolTip>
    <IconClass>font-icon-toggle-collapsed font-icon-collapsed font-icon-darkgreen font-icon-x1_3</IconClass>
  </CommandMenuItem>

</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/BriefcaseEntityTreeContextCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>briefcaseCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>280</Width>
  
  <EnableAdaptivity>false</EnableAdaptivity>
  
  <CommandMenuItem>
    <Text></Text>
    <BeginGroup>true</BeginGroup>
    <CommandName>addBriefcaseItem</CommandName>
    <Name>addBriefcaseItem</Name>
    <ToolTip>Добавить элемент в портфель</ToolTip>
    <IconClass>font-icon-addBriefcaseItem font-icon-color-darkblue font-icon-x1_2 indent-right-5px</IconClass>
  </CommandMenuItem>

  <CommandMenuItem>
    <Text></Text>
    <BeginGroup>true</BeginGroup>
    <CommandName>addBriefcaseChildItems</CommandName>
    <Name>removeBriefcaseItem</Name>
    <ToolTip>Удалить элемент из портфеля</ToolTip>
    <IconClass>font-icon-removeBriefcaseItem font-icon-color-darkred font-icon-x1_2 indent-right-5px</IconClass>
    <AdditionalInfo>BriefcaseItem</AdditionalInfo>
  </CommandMenuItem>


  
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/MeasurementDeviceGridContextCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>checkConnectionContextCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>220</Width>
  
  <CommandMenuItem>
    <Name>checkConnectionWithMeasurementDevice</Name>
    <Text>Проверка связи с устройством</Text>
    <CommandName>checkConnectionWithMeasurementDevice</CommandName> 
    <IconClass>font-icon-measurement-device font-icon-darkslateblue indent-right-5px</IconClass>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>checkConnectionWithAccessPoint</Name>
    <Text>Проверка связи с точкой доступа</Text>
    <CommandName>checkConnectionWithAccessPoint</CommandName>    
    <IconClass>font-icon-access-point font-icon-color-darkred indent-right-5px</IconClass>
  </CommandMenuItem>
 </CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/QueryCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>gridCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>350</Width>
  
   <CommandMenuItem>
      <ToolTip>Перестроить</ToolTip>
      <CommandName>rebuild</CommandName>
      <Name>rebuild</Name>
      <BeginGroup>true</BeginGroup>
      <IconClass>font-icon-rebuild font-icon-x1_2 font-icon-darkgreen</IconClass>
  </CommandMenuItem>
      
  <CommandMenuItem>
    <Text></Text>
    <CommandName>refresh</CommandName>
    <ToolTip>Обновить содержимое</ToolTip>
    <BeginGroup>true</BeginGroup>
    <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    
    <Text>Операции</Text>    
      <CommandMenuItem>
      <Text>Обновить</Text>
      <CommandName>refresh</CommandName>
      <Name>refresh</Name>
      <BeginGroup>true</BeginGroup>
      <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
    </CommandMenuItem>
    
    <CommandMenuItem>
      <Text>Отобразить поля</Text>
      <CommandName>showCustomizationWindow</CommandName>
      <Name>showCustomizationWindow</Name>
      <BeginGroup>true</BeginGroup>
      <IconClass>dev-icon-Customization_16x16  indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>gridExport</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>gridExport</CommandName>
    <IconClass>font-icon-file_export font-icon-x1_2 font-icon-darkslateblue</IconClass>
    <ToolTip>Экспорт</ToolTip>

    <CommandMenuItem>
      <Text>Формат Csv</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Csv</AdditionalInfo>
      <IconClass>dev-icon-ExportToCSV_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Формат Pdf</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Pdf</AdditionalInfo>
      <IconClass>dev-icon-ExportToPDF_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Формат Rtf</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Rtf</AdditionalInfo>
      <IconClass>dev-icon-ExportToRTF_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Формат Xls</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Xls</AdditionalInfo>
      <IconClass>dev-icon-ExportToXLS_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Формат Xlsx</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Xlsx</AdditionalInfo>
      <IconClass>dev-icon-ExportToXLSX_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>gridSettings</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>gridSettings</CommandName>
    <IconClass>font-icon-options font-icon-x1_2 font-icon-color-marine</IconClass>
    <ToolTip>Настройки</ToolTip>
    <CommandMenuItem>
      <Text>Формат данных</Text>
      <CommandName>showDisplayFormatDialog</CommandName>
      <Name>showDisplayFormatDialog</Name>
      <IconClass>dev-icon-DisplayFormat_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
  
</CommandMenu>
