=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/CommandMenu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="CommandMenuItem">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element ref="CommandMenuItem"/>
        <xs:element name="Name" type="xs:string"/>
        <xs:element name="AdditionalInfo" type="xs:string"/>
        <xs:element name="BeginGroup" type="xs:boolean"/>
        <xs:element name="CommandName" type="xs:string"/>
        <xs:element name="Enabled" type="xs:boolean" minOccurs="0"/>
        <xs:element minOccurs="0" name="Visible" type="xs:boolean"/>
        <xs:element name="IconClass" type="xs:string" minOccurs="0"/>
        <xs:element name="DropDownMode" type="xs:boolean" minOccurs="0"/>
        <xs:element name="TryMergeByName" type="xs:boolean" minOccurs="0"/>
        <xs:element name="Text" type="xs:string"/>
        <xs:element name="ToolTip" type="xs:string"/>
        <xs:element name="Checked" type="xs:boolean" minOccurs="0"/>
        <xs:element name="GroupName" type="xs:string" minOccurs="0"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="CommandMenu">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:string"/>
        <xs:element name="ClientVisible" type="xs:boolean"/>
        <xs:element maxOccurs="1" minOccurs="1" name="Width" type="xs:int"/>
        <xs:element name="EnableAdaptivity" type="xs:boolean"/>

        <xs:element maxOccurs="unbounded" minOccurs="0" ref="CommandMenuItem"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/EmergencySituationGridViewCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>emergencySituationGridViewCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>325</Width>
  <EnableAdaptivity>false</EnableAdaptivity>
  
  <CommandMenuItem>
    <Name>refresh</Name>
    <CommandName>refresh</CommandName>
    <ToolTip>Обновить содержимое</ToolTip>
    <IconClass>font-icon-refresh font-icon-darkslateblue font-icon-x1_2 indent-right-5px</IconClass>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>userAdditionalInfo</Name>
    <CommandName>userAdditionalInfo</CommandName>
    <Text></Text>
    <ToolTip>Изменить/создать "Сведения о пользователе"</ToolTip>
    <IconClass>font-icon-user-additional-info font-icon-darkgreen font-icon-x1_2 indent-right-5px</IconClass>
  </CommandMenuItem>
    
  <CommandMenuItem>
    <Text></Text>
    <CommandName>editEmergencySituation</CommandName>
    <Name>editEmergencySituation</Name>
    <ToolTip>Редактировать нештатную ситуацию канала</ToolTip>
    <IconClass>font-icon-edit font-icon-black font-icon-x1_2 indent-right-5px</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Text></Text>
    <CommandName>addEmergencySituation</CommandName>
    <Name>addEmergencySituation</Name>
    <ToolTip>Присоединить нештатную ситуацию к каналу</ToolTip>
    <IconClass>font-icon-plus font-icon-darkblue font-icon-x1_2 indent-right-5px</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Text></Text>
    <BeginGroup>true</BeginGroup>
    <CommandName>removeEmergencySituation</CommandName>
    <Name>removeEmergencySituation</Name>
    <ToolTip>Отсоединить нештатную ситуацию от канала</ToolTip>
    <IconClass>font-icon-minus font-icon-color-darkred font-icon-x1_2 indent-right-5px</IconClass>    
  </CommandMenuItem>

  <CommandMenuItem>
    <Text></Text>
    <CommandName>showHistory</CommandName>
    <IconClass>font-icon-history font-icon-color-darkred font-icon-x1_2 indent-right-5px</IconClass>
    <ToolTip>Показать историю изменений</ToolTip>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>showDeletedEntityLog</Name>
    <CommandName>showDeletedEntityLog</CommandName>
    <Text></Text>
    <ToolTip>Показать протокол удаленных сущностей</ToolTip>
    <IconClass>font-icon-deletedentitylog font-icon-slateblue font-icon-x1_3</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>exportEmergencyLog</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>exportEmergencyLog</CommandName>
    <IconClass>font-icon-file_export font-icon-darkslateblue font-icon-x1_2 indent-right-5px</IconClass>
    <ToolTip>Экспорт</ToolTip>
       
    <CommandMenuItem>
      <Text>Формат Xlsx</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Xlsx</AdditionalInfo>
      <IconClass>dev-icon-ExportToXLSX_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
  
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/GridCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>gridCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>330</Width>
  <CommandMenuItem>
    <Text></Text>
    <CommandName>create</CommandName>
    <ToolTip>Создать элемент словаря</ToolTip>
    <Name>create_1</Name>
    <IconClass>font-icon-plus font-icon-x1_3 font-icon-color-darkgreen</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Text></Text>
    <CommandName>refresh</CommandName>
    <ToolTip>Обновить содержимое</ToolTip>
    <BeginGroup>true</BeginGroup>
    <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Text>Операции</Text>
    <CommandMenuItem>
      <Text>Создать</Text>
      <CommandName>create</CommandName>
      <Name>create_2</Name>
      <IconClass>font-icon-plus font-icon-x1_3 font-icon-color-darkgreen</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Изменить</Text>
      <Enabled>false</Enabled>
      <Name>update</Name>
      <CommandName>update</CommandName>
      <IconClass>font-icon-edit2 font-icon-x1_2 indent-right-5px font-icon-black</IconClass>
      <BeginGroup>true</BeginGroup>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Удалить</Text>
      <Enabled>false</Enabled>
      <Name>remove</Name>
      <CommandName>remove</CommandName>
      <IconClass>font-icon-remove2 font-icon-x1_2 indent-right-5px font-icon-color-darkred</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Обновить</Text>
      <CommandName>refresh</CommandName>
      <Name>refresh</Name>
      <BeginGroup>true</BeginGroup>
      <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Отобразить поля</Text>
      <CommandName>showCustomizationWindow</CommandName>
      <Name>showCustomizationWindow</Name>
      <BeginGroup>true</BeginGroup>
      <IconClass>font-icon-customization font-icon-x1_2 font-icon-color-marine</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>gridExport</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>gridExport</CommandName>    
    <IconClass>font-icon-file_export font-icon-x1_2 font-icon-darkslateblue</IconClass>
    <ToolTip>Экспорт</ToolTip>
    
    <CommandMenuItem>
      <Text>Формат Csv</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Csv</AdditionalInfo>
      <IconClass>dev-icon-ExportToCSV_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Формат Xlsx</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Xlsx</AdditionalInfo>
      <IconClass>font-icon-xlsx</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Формат Pdf</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Pdf</AdditionalInfo>
      <IconClass>font-icon-pdf</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Формат Rtf</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Rtf</AdditionalInfo>
      <IconClass>font-icon-rtf</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Формат Xls</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Xls</AdditionalInfo>
      <IconClass>font-icon-xls</IconClass>
    </CommandMenuItem>    
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>gridSettings</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>gridSettings</CommandName>
    <IconClass>font-icon-options font-icon-x1_2 font-icon-color-marine</IconClass>
    <ToolTip>Настройки</ToolTip>
    <CommandMenuItem>
      <Text>Формат данных</Text>
      <CommandName>showDisplayFormatDialog</CommandName>
      <Name>showDisplayFormatDialog</Name>
      <IconClass></IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/FormCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  
  <Name>formCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>600</Width>
  <CommandMenuItem>
    <Text></Text>
    <CommandName>create</CommandName>
    <ToolTip>Создать новую запись</ToolTip>
    <Name>create</Name>
    <IconClass>font-icon-plus font-icon-x1_3 font-icon-color-darkgreen</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Text></Text>
    <CommandName>clone</CommandName>
    <ToolTip>Клонировать текущую запись</ToolTip>
    <Name>clone</Name>
    <IconClass>font-icon-clone font-icon-x1_3 font-icon-color-darkorange</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Text></Text>
    <Name>save</Name>
    <CommandName>update</CommandName>
    <ToolTip>Сохранить</ToolTip>
    <BeginGroup>true</BeginGroup>
    <IconClass>font-icon-floppy-save font-icon-x1_3 font-icon-color-navy</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>formExport</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>gridExport</CommandName>
    <IconClass>font-icon-file_export font-icon-x1_2 font-icon-darkslateblue</IconClass>
    <ToolTip>Экспорт</ToolTip>
    
    <CommandMenuItem>
      <Text>Формат Xlsx</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Xlsx</AdditionalInfo>
      <IconClass>dev-icon-ExportToXLSX_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
  
  <CommandMenuItem>
    
    <Name>removeGroup</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>removeGroup</CommandName>
    <IconClass>font-icon-remove2 font-icon-x1_2 indent-right-5px font-icon-color-darkred</IconClass>
    <ToolTip>Удалить</ToolTip>

    <CommandMenuItem>
      <Text>Удаление...</Text>
      <Name>remove</Name>
      <CommandName>remove</CommandName>
      <ToolTip>Удаление...</ToolTip>
      <IconClass>font-icon-remove2 font-icon-x1_2 indent-right-5px font-icon-color-darkred</IconClass>
    </CommandMenuItem>
    
    <CommandMenuItem>
      <Text>Каскадно связные сущности...</Text>
      <Name>cascadeDeleteEntityInfo</Name>
      <CommandName>cascadeDeleteEntityInfo</CommandName>
      <ToolTip>Показать информацию о каскадно удаляемых сущностях</ToolTip>
      <IconClass>font-icon-circle_info font-icon-x1_2 font-icon-darkslateblue</IconClass>
    </CommandMenuItem>
    
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Text></Text>
    <Name>cancel</Name>
    <CommandName>cancel</CommandName>
    <ToolTip>Отменить создание или клонирование</ToolTip>
    <IconClass>font-icon-undo font-icon-x1_3 font-icon-lightblue font-icon-bold</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Text></Text>
    <Name>refresh</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <ToolTip>Обновить текущую запись</ToolTip>
    <CommandName>renew</CommandName>
    <IconClass>font-icon-refreshform font-icon-darkblue font-icon-x1_3</IconClass>

    <CommandMenuItem>
      <Text>Обновить текущую запись</Text>
      <CommandName>renew</CommandName>
      <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkred</IconClass>
    </CommandMenuItem>
    
    <CommandMenuItem>
      <Text>Обновить форму</Text>
      <CommandName>refresh</CommandName>      
      <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
    </CommandMenuItem>

    </CommandMenuItem>
  
  <CommandMenuItem>
    <Text></Text>
    <Name>showJournal</Name>
    <CommandName>showJournal</CommandName>
    <ToolTip>Показать журнал записей</ToolTip>
    <IconClass>font-icon-query font-icon-x1_3 font-icon-black</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>openLinkInNewTab</Name>
    <CommandName>openLinkInNewTab</CommandName>
    <ToolTip>Открыть в новой вкладке...</ToolTip>
    <IconClass>font-icon-new-window font-icon-darkred font-icon-x1_2</IconClass>
  </CommandMenuItem>

 <CommandMenuItem>
    <Name>doSyncWithTree</Name>
    <CommandName>doSyncWithTree</CommandName>
    <ToolTip>Синхронизировать с деревом</ToolTip>
    <IconClass>font-icon-tree font-icon-x1_2 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>

   <CommandMenuItem>
    <Text></Text>
    <Name>showDynamicData</Name>
    <CommandName>showDynamicData</CommandName>
    <ToolTip>Динамические параметры</ToolTip>
    <IconClass>font-icon-dynamic font-icon-x1_3 font-icon-red</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Text>Вид</Text>    
    <CommandMenuItem>
      <Text>Свернуть все группы</Text>
      <IconClass>font-icon-circle_arrow_up indent-right-5px</IconClass>
      <CommandName>collapseAllGroups</CommandName>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Развернуть все группы</Text>
      <IconClass>font-icon-circle_arrow_down indent-right-5px</IconClass>
      <CommandName>expandAllGroups</CommandName>
    </CommandMenuItem>
  </CommandMenuItem>
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/BriefcaseCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>briefcaseCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>300</Width>
  
  <EnableAdaptivity>false</EnableAdaptivity>
  
  <CommandMenuItem>
    <Text></Text>
    <CommandName>addBriefcase</CommandName>
    <Name>addBriefcase</Name>
    <ToolTip>Добавить новый портфель...</ToolTip>
    <IconClass>font-icon-addBriefcase font-icon-darkblue font-icon-x1_2 indent-right-5px</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Text></Text>
    <BeginGroup>true</BeginGroup>
    <CommandName>removeBriefcase</CommandName>
    <Name>removeBriefcase</Name>
    <ToolTip>Удалить выбранный портфель</ToolTip>
    <IconClass>font-icon-removeBriefcase font-icon-color-darkred font-icon-x1_2 indent-right-5px</IconClass>
    <AdditionalInfo>Briefcase</AdditionalInfo>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Text></Text>
    <BeginGroup>true</BeginGroup>
    <CommandName>addBriefcaseItem</CommandName>
    <Name>addBriefcaseItem</Name>
    <ToolTip>Добавить элемент в портфель</ToolTip>
    <IconClass>font-icon-addBriefcaseItem font-icon-color-darkblue font-icon-x1_2 indent-right-5px</IconClass>
  </CommandMenuItem>

  <CommandMenuItem>
    <Text></Text>
    <BeginGroup>true</BeginGroup>
    <CommandName>removeBriefcaseItem</CommandName>
    <Name>removeBriefcaseItem</Name>
    <ToolTip>Удалить элемент из портфеля</ToolTip>
    <IconClass>font-icon-removeBriefcaseItem font-icon-color-darkred font-icon-x1_2 indent-right-5px</IconClass>
    <AdditionalInfo>BriefcaseItem</AdditionalInfo>
  </CommandMenuItem>

  <CommandMenuItem>
    <Text></Text>
    <BeginGroup>true</BeginGroup>
    <CommandName>groupBriefcaseItemByEntityName</CommandName>
    <Name>groupBriefcaseItemByEntityName</Name>
    <ToolTip>Группировать / разгруппировать по типу сущности</ToolTip>
    <IconClass>font-icon-groupBriefcaseItemByEntityName font-icon-x1_2 font-icon-darkslateblue indent-right-5px</IconClass>
    <AdditionalInfo>BriefcaseItem</AdditionalInfo>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>gridExport</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>gridExport</CommandName>
    <IconClass>font-icon-file_export font-icon-x1_2 font-icon-darkslateblue</IconClass>
    <ToolTip>Экспорт</ToolTip>

    <CommandMenuItem>
      <Text>Формат Xlsx</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Xlsx</AdditionalInfo>
      <IconClass>dev-icon-ExportToXLSX_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>

  <CommandMenuItem>
    <Text></Text>
    <CommandName>toggleCollapse</CommandName>
    <Name>toggleCollapse</Name>
    <ToolTip>Свернуть/развернуть окно</ToolTip>
    <IconClass>font-icon-toggle-collapsed font-icon-collapsed font-icon-darkgreen font-icon-x1_3</IconClass>
  </CommandMenuItem>
  
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/FormJournalDialogMultipleToMultipleLinkEntityCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>formJournalDialogMultipleToMultipleLinkEntityCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>250</Width>
  
  <CommandMenuItem>
    <Name>refresh</Name>
    <CommandName>refresh</CommandName>
    <ToolTip>Обновить содержимое</ToolTip>
    <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>formJournalExport</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>gridExport</CommandName>
    <IconClass>font-icon-file_export font-icon-x1_2 font-icon-darkslateblue</IconClass>
    <ToolTip>Экспорт</ToolTip>

    <CommandMenuItem>
      <Text>Формат Xlsx</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Xlsx</AdditionalInfo>
      <IconClass>font-icon-xlsx indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
    
  <CommandMenuItem>
    <Text></Text>
    <BeginGroup>true</BeginGroup>
    <CommandName>removeMultipleToMultipleLinkEntity</CommandName>
    <Name>removeMultipleToMultipleLinkEntity</Name>
    <IconClass>font-icon-remove2 font-icon-x1_2 indent-right-5px font-icon-color-darkred</IconClass>
  </CommandMenuItem>
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/EntityTreeCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>entityTreeCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>220</Width>
  <CommandMenuItem>
    <Name>view</Name>
    <Text>Вид</Text>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Text></Text>
    <Name>refresh</Name>
    <CommandName>refresh</CommandName>
    <IconClass>font-icon-refresh font-icon-x1_2 font-icon-darkslateblue</IconClass>
    <ToolTip>Перестроить дерево</ToolTip>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>showSearchPanel</Name>
    <Text></Text>
    <CommandName>showSearchPanel</CommandName>
    <IconClass>font-icon-search2 font-icon-x1_2 font-icon-darkgreen</IconClass>
    <GroupName>showSearchPanel</GroupName>
    <ToolTip>Показать панель поиска</ToolTip>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>expandAll</Name>
    <Text></Text>
    <CommandName>expandAll</CommandName>
    <ToolTip>Развернуть дерево</ToolTip>
    <IconClass>font-icon-tree-expand-all font-icon-slategray</IconClass>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>collapseAll</Name>
    <Text></Text>
    <CommandName>collapseAll</CommandName>
    <ToolTip>Свернуть дерево</ToolTip>
    <IconClass>font-icon-tree-collapse-all font-icon-slategray</IconClass>
  </CommandMenuItem>
 </CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/DynamicParameterValueParametricDialogCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>dynamicParameterValueParametricDialogCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>50</Width>  
  <CommandMenuItem>
    <Text></Text>
    <BeginGroup>true</BeginGroup>
    <CommandName>addDynamicParameter</CommandName>
    <Name>addDynamicParameter</Name>
    <IconClass>font-icon-plus font-icon-x1_3 font-icon-color-darkgreen</IconClass>
  </CommandMenuItem>
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/DashboardPlacementLevelMnemoschemeCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>dashboardCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>295</Width>

  <CommandMenuItem>
    <Name>refresh</Name>
    <CommandName>refresh</CommandName>
    <ToolTip>Обновить содержимое</ToolTip>
    <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>mapLocation</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <ToolTip>Карта</ToolTip>
    <CommandName>mapLocation</CommandName>
    <Text></Text>
    <IconClass>font-icon-location-map font-icon-x1_3 font-icon-moor </IconClass>

    <CommandMenuItem>
      <Name>showOnMap</Name>
      <ToolTip>Показать строение на карте</ToolTip>
      <CommandName>showOnMap</CommandName>
      <Text>Показать строение на карте</Text>
      <IconClass>font-icon-location-map font-icon-x1_3 font-icon-moor indent-right-5px</IconClass>
    </CommandMenuItem>

    <CommandMenuItem>
      <Name>gotoMap</Name>
      <ToolTip>Перейти к карте объектов</ToolTip>
      <Text>Перейти к карте объектов</Text>
      <CommandName>gotoMap</CommandName>
      <IconClass>font-icon-map font-icon-x1_3 font-icon-color-red indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>gotoEntityTree</Name>
    <ToolTip>Синхронизировать с деревом</ToolTip>
    <CommandName>gotoEntityTree</CommandName>
    <IconClass>font-icon-tree font-icon-x1_2 font-icon-darkslateblue indent-right-5px</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>mnemoschemeImageExport</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>mnemoschemeImageExport</CommandName>
    <IconClass>font-icon-file_export font-icon-x1_2 font-icon-darkslateblue</IconClass>
    <ToolTip>Экспорт</ToolTip>

    <CommandMenuItem>
      <Text>Формат Xlsx</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>xlsx</AdditionalInfo>
      <IconClass>dev-icon-ExportToXLSX_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
    
    <CommandMenuItem>
      <Text>Формат Svg</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>svg</AdditionalInfo>
      <IconClass>dev-icon-ExportToXML_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
  
</CommandMenu>
