=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/CommandMenu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="CommandMenuItem">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element ref="CommandMenuItem"/>
        <xs:element name="Name" type="xs:string"/>
        <xs:element name="AdditionalInfo" type="xs:string"/>
        <xs:element name="BeginGroup" type="xs:boolean"/>
        <xs:element name="CommandName" type="xs:string"/>
        <xs:element name="Enabled" type="xs:boolean" minOccurs="0"/>
        <xs:element minOccurs="0" name="Visible" type="xs:boolean"/>
        <xs:element name="IconClass" type="xs:string" minOccurs="0"/>
        <xs:element name="DropDownMode" type="xs:boolean" minOccurs="0"/>
        <xs:element name="TryMergeByName" type="xs:boolean" minOccurs="0"/>
        <xs:element name="Text" type="xs:string"/>
        <xs:element name="ToolTip" type="xs:string"/>
        <xs:element name="Checked" type="xs:boolean" minOccurs="0"/>
        <xs:element name="GroupName" type="xs:string" minOccurs="0"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="CommandMenu">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:string"/>
        <xs:element name="ClientVisible" type="xs:boolean"/>
        <xs:element maxOccurs="1" minOccurs="1" name="Width" type="xs:int"/>
        <xs:element name="EnableAdaptivity" type="xs:boolean"/>

        <xs:element maxOccurs="unbounded" minOccurs="0" ref="CommandMenuItem"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/MapDiagrammDialogContextCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>mapDiagrammDialogContextCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>220</Width>
  
  <CommandMenuItem>
    <Name>percentageToggle</Name>
    <Text>Показать персентаж</Text>
    <CommandName>percentageToggle</CommandName>
    <Checked>false</Checked>
    <GroupName>percentageToggleGroup</GroupName>
  </CommandMenuItem>
  
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/DashboardCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>dashboardCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>450</Width>
  <CommandMenuItem>
    <Name>refresh</Name>
    <CommandName>refresh</CommandName>
    <ToolTip>Обновить содержимое</ToolTip>
    <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>showHistory</Name>
    <CommandName>showHistory</CommandName>
    <ToolTip>Показать историю изменений</ToolTip>
    <IconClass>font-icon-history font-icon-color-darkred font-icon-x1_3</IconClass>
    <Visible>false</Visible>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>gotoMap</Name>
    <ToolTip>Перейти к карте объектов</ToolTip>
    <Text />
    <CommandName>gotoMap</CommandName>
    <IconClass>font-icon-map font-icon-x1_2 font-icon-color-red indent-right-5px</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>showOnMap</Name>
    <ToolTip>Показать строение на карте</ToolTip>
    <CommandName>showOnMap</CommandName>
    <Text />
    <IconClass>font-icon-location-map font-icon-x1_3 font-icon-moor indent-right-5px</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>gotoEntityTree</Name>
    <ToolTip>Синхронизировать с деревом</ToolTip>
    <CommandName>gotoEntityTree</CommandName>
    <IconClass>font-icon-tree font-icon-x1_2 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>showOptions</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <ToolTip>Настройки</ToolTip>
    <CommandName>showOptions</CommandName>
    <Text />
    <IconClass>font-icon-options font-icon-x1_2 font-icon-darkslateblue indent-right-5px</IconClass>
    <CommandMenuItem>
      <Name>showParameters</Name>
      <Text>Выбрать параметры...</Text>
      <CommandName>showParameters</CommandName>
      <IconClass>font-icon-abstract-parameter font-icon-x1_2 font-icon-darkmagenta indent-right-5px</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Name>showInterval</Name>
      <Text>Временной интервал...</Text>
      <CommandName>showInterval</CommandName>
      <IconClass>font-icon-interval font-icon-x1_3 font-icon-black indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>showDiagrammDialog</Name>
    <CommandName>showDiagrammDialog</CommandName>
    <ToolTip>Диаграммы</ToolTip>
    <IconClass>font-icon-charts font-icon-x1_2 font-icon-lightblue</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>showArchiveJournal</Name>
    <CommandName>showArchiveJournal</CommandName>
    <AdditionalInfo>Archive</AdditionalInfo>
    <ToolTip>Журнал архивов устройства</ToolTip>
    <IconClass>font-icon-archive font-icon-x1_2 font-icon-orangered</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>readCurrents</Name>
    <CommandName>readCurrents</CommandName>
    <IconClass>font-icon-read-currents font-icon-darkgreen font-icon-x1_2</IconClass>
    <ToolTip>Чтение текущих значений</ToolTip>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>checkConnection</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>checkConnection</CommandName>
    <IconClass>font-icon-checkconnection font-icon-color-darkred indent-right-5px</IconClass>
    <ToolTip>Проверка связи</ToolTip>
    <CommandMenuItem>
      <Name>checkConnectionWithMeasurementDevice</Name>
      <Text>Проверка связи с устройством</Text>
      <CommandName>checkConnectionWithMeasurementDevice</CommandName>
      <IconClass>font-icon-measurement-device font-icon-darkslateblue indent-right-5px</IconClass>
    </CommandMenuItem>
    <CommandMenuItem>
      <Name>checkConnectionWithAccessPoint</Name>
      <Text>Проверка связи с точкой доступа</Text>
      <CommandName>checkConnectionWithAccessPoint</CommandName>
      <IconClass>font-icon-access-point font-icon-color-darkred indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>  
  <CommandMenuItem>
    <Name>gotoDashboardInNewTab</Name>
    <CommandName>gotoDashboardInNewTab</CommandName>
    <ToolTip>Открыть в новой вкладке...</ToolTip>
    <IconClass>font-icon-new-window font-icon-darkred font-icon-x1_2</IconClass>
  </CommandMenuItem>
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/AdminAreaNavBarContextCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>adminAreaNavBarContextCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>220</Width>  
  <CommandMenuItem>
    <Name>openLinkInNewTab</Name>
    <Text> Открыть в новой вкладке</Text>
    <CommandName>openLinkInNewTab</CommandName>
    <IconClass>font-icon-new-window font-icon-darkred font-icon-x1_2</IconClass>
  </CommandMenuItem>
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/MapCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>mapCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>380</Width>
  <CommandMenuItem>
    <Name>showMapOptions</Name>
    <CommandName>showMapOptions</CommandName>
    <IconClass>font-icon-options font-icon-x1_2 font-icon-color-marine</IconClass>
    <ToolTip>Настройки</ToolTip>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>mapFilterByCity</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>mapFilterByCity</CommandName>
    <IconClass>font-icon-map font-icon-x1_2 font-icon-slateblue</IconClass>
    <ToolTip>Фильтр строений по населенному пункту</ToolTip>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>mapFilter</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>mapFilter</CommandName>
    <IconClass>font-icon-checkconnection font-icon-x1_2 font-icon-slateblue</IconClass>
    <ToolTip>Фильтр строений на основе соостояния связи</ToolTip>
    <CommandMenuItem>
      <Text>Все строения</Text>
      <AdditionalInfo>3</AdditionalInfo>
      <CommandName>mapFilter</CommandName>
      <Name>mapFilterBlue</Name>
      <IconClass>font-icon-checkconnection font-icon-blue font-icon-x1_2</IconClass>
      <Checked>true</Checked>
      <GroupName>mapFilter</GroupName>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Связь отсутствует</Text>
      <CommandName>mapFilter</CommandName>
      <AdditionalInfo>2</AdditionalInfo>
      <Name>mapFilterRed</Name>
      <IconClass>font-icon-checkconnection font-icon-darkred font-icon-x1_2</IconClass>
      <Checked>false</Checked>
      <GroupName>mapFilter</GroupName>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Одна из точек доступа на связи</Text>
      <CommandName>mapFilter</CommandName>
      <AdditionalInfo>1</AdditionalInfo>
      <Name>mapFilterYellow</Name>
      <IconClass>font-icon-checkconnection font-icon-color-darkorange font-icon-x1_2</IconClass>
      <Checked>false</Checked>
      <GroupName>mapFilter</GroupName>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Точки доступа и устройства на связи</Text>
      <CommandName>mapFilter</CommandName>
      <AdditionalInfo>0</AdditionalInfo>
      <Name>mapFilterGreen</Name>
      <IconClass>font-icon-checkconnection font-icon-green font-icon-x1_2</IconClass>
      <Checked>false</Checked>
      <GroupName>mapFilter</GroupName>
    </CommandMenuItem>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>mapFilterByEmergency</Name>
    <Text>
    </Text>
    <CommandName>mapFilterByEmergency</CommandName>
    <AdditionalInfo>2</AdditionalInfo>
    <ToolTip>Фильтр строений с нештатными ситуациями</ToolTip>
    <IconClass>font-icon-emergency font-icon-x1_3 font-icon-slateblue</IconClass>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandMenuItem>
      <Text>Все строения</Text>
      <CommandName>mapFilterByEmergency</CommandName>
      <Name>mapFilterByEmergencyAll</Name>
      <AdditionalInfo>0</AdditionalInfo>
      <IconClass>font-icon-emergency font-icon-x1_2</IconClass>
      <Checked>true</Checked>
      <GroupName>mapFilterByEmergency</GroupName>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>С нештатными ситуациями</Text>
      <CommandName>mapFilterByEmergency</CommandName>
      <Name>mapFilterByEmergencyWith</Name>
      <AdditionalInfo>1</AdditionalInfo>
      <IconClass>font-icon-emergency font-icon-x1_2 font-icon-darkred</IconClass>
      <Checked>false</Checked>
      <GroupName>mapFilterByEmergency</GroupName>
    </CommandMenuItem>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>zoom1</Name>
    <Text>
    </Text>
    <CommandName>zoom</CommandName>
    <ToolTip>Центрировать карту (Ctrl+Click)</ToolTip>
    <IconClass>font-icon-fullscreen font-icon-x1_3 font-icon-steelblue</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Text>
    </Text>
    <Name>refresh1</Name>
    <ToolTip>Обновить и центрировать</ToolTip>
    <CommandName>refresh</CommandName>
    <IconClass>font-icon-refresh-markers font-icon-x1_3 indent-right-5px</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Name>showBuildings</Name>
    <CommandName>showBuildings</CommandName>
    <ToolTip>Список объектов учета</ToolTip>
    <IconClass>font-icon-search font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/ReadOnlyFormCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>formCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>515</Width>
  <CommandMenuItem>
    <Text></Text>
    <Name>remove</Name>
    <CommandName>remove</CommandName>
    <ToolTip>Удалить</ToolTip>
    <IconClass>dev-icon-Delete_16x16 indent-right-5px</IconClass>
  </CommandMenuItem>  
  <CommandMenuItem>
    <Text></Text>
    <Name>refresh</Name>
    <ToolTip>Обновить содержимое</ToolTip>
    <CommandName>refresh</CommandName>
    <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Text></Text>
    <Name>showJournal</Name>
    <CommandName>showJournal</CommandName>
    <ToolTip>Показать журнал записей</ToolTip>
    <IconClass>dev-icon-Journal_16x16 indent-right-5px</IconClass>
  </CommandMenuItem>
  <CommandMenuItem>
    <Text>Вид</Text>
    <CommandMenuItem>
      <Text>Свернуть все группы</Text>
      <IconClass>font-icon-circle_arrow_up indent-right-5px</IconClass>
      <CommandName>collapseAllGroups</CommandName>
    </CommandMenuItem>
    <CommandMenuItem>
      <Text>Развернуть все группы</Text>
      <IconClass>font-icon-circle_arrow_down indent-right-5px</IconClass>
      <CommandName>expandAllGroups</CommandName>
    </CommandMenuItem>
  </CommandMenuItem>
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/MapDiagrammDialogCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>mapDiagrammDialogCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>220</Width>

  <CommandMenuItem>
    <Name>selectDiagrammByType</Name>
    <CommandName>selectDiagrammBy</CommandName>
    <IconClass>font-icon-pie_chart font-icon-x1_3 font-icon-darkred</IconClass>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <ToolTip>Типы диаграмм</ToolTip>

    <CommandMenuItem>
      <AdditionalInfo>byDevice</AdditionalInfo>
      <GroupName>selectDiagrammByTypeGroup</GroupName>
      <Text>По типу прибора</Text>
      <CommandName>selectDiagrammByType</CommandName>
      <Name>selectDiagrammByDevice</Name>
      <Checked>true</Checked>
    </CommandMenuItem>

    <CommandMenuItem>
      <AdditionalInfo>byDistrict</AdditionalInfo>
      <GroupName>selectDiagrammByTypeGroup</GroupName>
      <Text>По районам</Text>
      <CommandName>selectDiagrammByType</CommandName>
      <Name>selectDiagrammByDistrict</Name>
    </CommandMenuItem>

    <CommandMenuItem>
      <AdditionalInfo>byConnectionQuality</AdditionalInfo>
      <GroupName>selectDiagrammByTypeGroup</GroupName>
      <Text>По качеству связи</Text>
      <CommandName>selectDiagrammByType</CommandName>
      <Name>selectDiagrammByDistrict</Name>
    </CommandMenuItem>
    
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>mapDiagrammExport</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>dashboardDiagrammExport</CommandName>
    <IconClass>font-icon-file_export font-icon-x1_2 font-icon-darkslateblue</IconClass>
    <ToolTip>Экспорт</ToolTip>

    <CommandMenuItem>
      <Text>Формат Xlsx</Text>
      <CommandName>exportXlsx</CommandName>
      <Name>exportToXlsx</Name>
      <IconClass>dev-icon-ExportToXLSX_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>

    <CommandMenuItem>
      <Text>Формат Svg</Text>
      <CommandName>exportSvg</CommandName>
      <Name>exportToSvg</Name>
      <IconClass>dev-icon-ExportToCSV_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>

</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/SendMailUserDialogCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  
  <Name>sendMailUserDialogCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>210</Width>
  <CommandMenuItem>
    <Text>Шаблоны</Text>
    <CommandMenuItem>
      <Text>Подтвержение регистрации</Text>
      <Name>newUserNotify</Name>
      <ToolTip>Сообщение о подтвержении регистрации нового пользователя</ToolTip>
      <CommandName>newUserNotify</CommandName>
      <IconClass>font-icon-user_add font-icon-x1_3 font-icon-darkslateblue</IconClass>
    </CommandMenuItem>

    <CommandMenuItem>
      <Text>Смена пароля</Text>
      <Name>changePasswordNotify</Name>
      <Text></Text>
      <CommandName>changePasswordNotify</CommandName>
      <ToolTip>Сообщение о смене пароля</ToolTip>
      <IconClass>font-icon-keys font-icon-x1_3 font-icon-color-darkred</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Text></Text>
    <Name>newUserNotify1</Name>
    <ToolTip>Сообщение о подтвержении регистрации нового пользователя</ToolTip>
    <CommandName>newUserNotify</CommandName>
    <IconClass>font-icon-user_add font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>changePasswordNotify1</Name>
    <Text></Text>
    <CommandName>changePasswordNotify</CommandName>
    <ToolTip>Сообщение о смене пароля</ToolTip>
    <IconClass>font-icon-keys font-icon-x1_3 font-icon-color-darkred</IconClass>    
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>clearMailMessage</Name>
    <Text></Text>
    <CommandName>clearMailMessage</CommandName>
    <ToolTip>Очистить</ToolTip>
    <IconClass>font-icon-remove_2 font-icon-x1_3 font-icon-color-metrohover</IconClass>
  </CommandMenuItem>
  
</CommandMenu>

=== MaximOkulin/EnergyTechAudit.PowerAccounting/EnergyTechAudit.PowerAccounting.Database/PostDeployment/_Xml/CommandMenus/MnemoschemeImageDialogCommandMenu.xml
<CommandMenu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CommandMenu.xsd">
  <Name>mnemoschemeImageDialogCommandMenu</Name>
  <ClientVisible>true</ClientVisible>
  <Width>250</Width>

  <CommandMenuItem>
    <Name>panZoomReset</Name>
    <CommandName>panZoomReset</CommandName>
    <ToolTip>Сброс масштаба</ToolTip>
    <IconClass>font-icon-zoom-reset font-icon-x1_3 font-icon-darkgreen</IconClass>
  </CommandMenuItem>
  
  <CommandMenuItem>
    <Name>refresh</Name>
    <CommandName>refresh</CommandName>
    <ToolTip>Обновить содержимое</ToolTip>
    <IconClass>font-icon-refresh font-icon-x1_3 font-icon-darkslateblue</IconClass>
  </CommandMenuItem>

  <CommandMenuItem>
    <Name>mnemoschemeImageExport</Name>
    <DropDownMode>true</DropDownMode>
    <BeginGroup>true</BeginGroup>
    <CommandName>mnemoschemeImageExport</CommandName>
    <IconClass>font-icon-file_export font-icon-x1_2 font-icon-darkslateblue</IconClass>
    <ToolTip>Экспорт</ToolTip>

    <CommandMenuItem>
      <Text>Формат Svg</Text>
      <CommandName>exportTo</CommandName>
      <AdditionalInfo>Xlsx</AdditionalInfo>
      <IconClass>dev-icon-ExportToXML_16x16 indent-right-5px</IconClass>
    </CommandMenuItem>
  </CommandMenuItem>
  
</CommandMenu>
